Java01. ДЗ 01, Кольцов Михаил, подгруппа 1
java-course-au/assignments-2017-1 pull request #10
Opened 2017-02-22 22:30 UTC by ItsLastDay

2017-02-22 22:33 UTC, ItsLastDay commented
@dzharkov

2017-02-25 09:25 UTC, dzharkov requested changes
Жду исправлений и ответов на вопросы до 02.03.2017 23:59

2017-02-25 09:25 UTC, dzharkov commented on src/main/java/ru/spbau/mit/StringSetImpl.java
> +    private ArrayList<int[]> nextState = new ArrayList<>();
Может быть все-таки завести private static класс для хранения состояния вершины бора?

2017-02-25 09:25 UTC, dzharkov commented on src/main/java/ru/spbau/mit/StringSetImpl.java
> +    private static final int JUMP_SIZE = 256 * 2;    // Java has 2-byte chars.
Но у нас ведь алфавит ограничен

2017-02-25 09:25 UTC, dzharkov commented on src/main/java/ru/spbau/mit/StringSetImpl.java
> +    private void addPrefixVal(String element, int addend) {
Я не смог найти значение слова `addend`

2017-02-25 09:51 UTC, ItsLastDay commented on src/main/java/ru/spbau/mit/StringSetImpl.java
> +    private void addPrefixVal(String element, int addend) {
https://en.wiktionary.org/wiki/addend#English

2017-02-26 18:40 UTC, ItsLastDay commented
@dzharkov 
Сделал внутренний класс для хранения вершины бора, исправил размер алфавита.  
Слово `addend` означает `слагаемое` (https://en.wiktionary.org/wiki/addend#English).

2017-03-07 06:00 UTC, dzharkov commented
Ок, 10/10

2017-03-07 06:00 UTC, closed without merging