Java01. ДЗ 07, Лапицкая Людмила, подгруппа 1
java-course-au/assignments-2017-1 pull request #102
Opened 2017-05-17 11:49 UTC by bugogish

@dzharkov

2017-05-21 08:07 UTC, dzharkov requested changes
Жду исправлений и ответов на вопросы до 26.05.2017 23:59

2017-05-21 08:07 UTC, dzharkov commented on src/main/java/ru/spbau/mit/SimpleImplementor.java
> +        try (BufferedWriter writer = new BufferedWriter(new FileWriter(file))) {
Можно воспользоваться FileUtils.writeStringToFile, а еще стоило бы весь try-catch вынести в отдельный метод, чтобы избежать дублирования

2017-05-21 08:07 UTC, dzharkov commented on src/main/java/ru/spbau/mit/SimpleImplementor.java
> +        Set<String> methodsImpl = new HashSet<>();
Почему именно множество, и почему `generateMethodsForClass` его не возвращает, а именно заполняет?

2017-05-21 08:07 UTC, dzharkov commented on src/main/java/ru/spbau/mit/SimpleImplementor.java
> +        List<String> methodImpl = new ArrayList<>();
Может тогда `StringBuilder`?

2017-05-21 08:07 UTC, dzharkov commented on src/main/java/ru/spbau/mit/SimpleImplementor.java
> +        return Stream.of(parameters).
:+1:

2017-05-22 14:27 UTC, bugogish commented on src/main/java/ru/spbau/mit/SimpleImplementor.java
> +        Set<String> methodsImpl = new HashSet<>();
Именно множество потому что может быть такая ситуация:
В интерфейсе есть какой-то метод: void method();
Абстрактный класс имплементит этот интерфейс и переопределяет этот метод, но оставляет его абстрактным: public abstract void method();
В таком случае код - реализация такого абстрактного класса, сгенерированная моим Implementor-ом не скомпилится, если сделать просто список, потому что он переопределит и первый и второй.
Такая ситуация есть, например, в AbstractCollection с size и iterator.
С заполнением множества - просто, чтобы не сливать постоянно множества, возвращенные из рекурсивных вызовов

2017-05-24 12:37 UTC, bugogish commented on src/main/java/ru/spbau/mit/SimpleImplementor.java
> +        List<String> methodImpl = new ArrayList<>();
@dzharkov Тогда придется пробелы вручную везде проставлять :(

2017-05-27 09:09 UTC, dzharkov commented
Ок, 10/10

2017-05-27 09:09 UTC, closed without merging