Java01. ДЗ 07, Гардер Антон, подгруппа 1
java-course-au/assignments-2017-1 pull request #103
Opened 2017-05-17 15:44 UTC by avgarder

2017-05-17 16:34 UTC, avgarder commented
@dzharkov

2017-05-21 08:18 UTC, dzharkov requested changes
Жду исправлений и ответов на вопросы до 26.05.2017 23:59

2017-05-21 08:18 UTC, dzharkov commented on src/main/java/ru/spbau/mit/SimpleImplementor.java
> +        generateCode(clazz, clazz.getPackage());
Мне кажется, было бы логичнее, чтобы `generateCode` возвращал имя класса

2017-05-21 08:18 UTC, dzharkov commented on src/main/java/ru/spbau/mit/SimpleImplementor.java
> +            if (Modifier.isFinal(clazz.getModifiers())) {
Я бы вынес содержимое try в отдельный метод, так код приятней читается, без лишнего отступа

2017-05-21 08:18 UTC, dzharkov commented on src/main/java/ru/spbau/mit/SimpleImplementor.java
> +    private void generateCode(Class<?> clazz, Package pack) throws ImplementorException {
Лучше не использовать сокращения, которые совпадают с другими словами

2017-05-21 08:18 UTC, dzharkov commented on src/main/java/ru/spbau/mit/SimpleImplementor.java
> +            if (Modifier.isFinal(clazz.getModifiers())) {
Вообще этот метод было бы прикольно разбить на отдельные логические блоки:
1. Делаем одно
2. Делаем второе
3. ...

2017-05-21 08:18 UTC, dzharkov commented on src/main/java/ru/spbau/mit/SimpleImplementor.java
> +                    if (i != 0) {
Очень хочется снизить баллы за вот эти пляски с циклами, когда есть стримы, но не буду

2017-05-21 08:18 UTC, dzharkov commented on src/main/java/ru/spbau/mit/SimpleImplementor.java
> +                    continue;
А такое вообще возможно?

2017-05-27 09:10 UTC, dzharkov commented
Нет исправлений, 5/10

2017-05-27 09:10 UTC, closed without merging