Add SimpleImplementor
java-course-au/assignments-2017-1 pull request #104
Opened 2017-05-18 06:23 UTC by ISilence

2017-05-21 08:43 UTC, dzharkov requested changes
Жду исправлений и ответов на вопросы до 26.05.2017 23:59

2017-05-21 08:43 UTC, dzharkov commented on src/main/java/ru/spbau/mit/SimpleImplementor.java
> +            FileWriter fw = new FileWriter(fd);
Можно воспользоваться FileUtils.writeStringToFile

2017-05-21 08:43 UTC, dzharkov commented on src/main/java/ru/spbau/mit/SimpleImplementor.java
> +    private StringBuilder builder;
Не очень правильно хранить это как состояние в `SimpleImplementor`
Как минимум класс становится не thread-safe, хотя по идее предпосылок к этому нет.
Можно либо выделить отдельный класс-билдер с методами `generateClassHeader`, `generateMethod` и т.д., либо передавать во все методы `StringBuilder`

2017-05-21 08:43 UTC, dzharkov commented on src/main/java/ru/spbau/mit/SimpleImplementor.java
> +        mbuilder.append(params[0].getCanonicalName());
Насколько более естественно это можно было бы сделать со стримами..

2017-05-21 08:43 UTC, dzharkov commented on src/main/java/ru/spbau/mit/SimpleImplementor.java
> +        HashSet<String> methods = new HashSet<>();
Классы-реализации лучше не использовать в типах

2017-05-21 08:43 UTC, dzharkov commented on src/main/java/ru/spbau/mit/SimpleImplementor.java
> +            for (Class interfacezz : clazz.getInterfaces()) {
От обработки интерфейсов можно избавиться, воспользовавшись приятным свойством: в них все методы публичные

2017-05-22 19:07 UTC, ISilence commented
@dzharkov, исправил

2017-05-27 09:11 UTC, dzharkov commented
Ок, 10/10

2017-05-27 09:11 UTC, closed without merging