Java01. ДЗ 07, Ёров Собир, подгруппа 1
java-course-au/assignments-2017-1 pull request #105
Opened 2017-05-18 16:21 UTC by YorovSobir

@dzharkov

2017-05-21 08:49 UTC, dzharkov requested changes
Жду исправлений и ответов на вопросы до 26.05.2017 23:59

2017-05-21 08:49 UTC, dzharkov commented on src/main/java/ru/spbau/mit/SimpleImplementor.java
> +            if (!Files.exists(pathToImpl.getParent())) {
Избавься от дублирования кода

2017-05-21 08:49 UTC, dzharkov commented on src/main/java/ru/spbau/mit/SimpleImplementor.java
> +        return createClassName(classImpl, baseClass)
Почему конкатенация строк в большинстве случаев не поощряется?
Как это можно исправить?

2017-05-21 08:49 UTC, dzharkov commented on src/main/java/ru/spbau/mit/SimpleImplementor.java
> +            Arrays.stream(cur.getInterfaces())
От обработки интерфейсов можно избавиться, воспользовавшись приятным свойством: в них все методы публичные

2017-05-21 08:49 UTC, dzharkov commented on src/main/java/ru/spbau/mit/SimpleImplementor.java
> +        List<String> methods = new ArrayList<>();
В интерфейсах и классах могут встречаться методы с одинаковой сигнатурой

2017-05-21 08:49 UTC, dzharkov commented on src/main/java/ru/spbau/mit/SimpleImplementor.java
> +        // compiler will use StringBuilder automatically
Здесь может быть, но в итоге у тебя каждый метод -- это отдельная строка

2017-05-21 08:49 UTC, dzharkov commented on src/main/java/ru/spbau/mit/SimpleImplementor.java
> +        return Arrays.stream(params)
:+1:

2017-05-24 21:49 UTC, YorovSobir commented on src/main/java/ru/spbau/mit/SimpleImplementor.java
> +            if (!Files.exists(pathToImpl.getParent())) {
Исправил

2017-05-24 21:55 UTC, YorovSobir commented on src/main/java/ru/spbau/mit/SimpleImplementor.java
> +        return createClassName(classImpl, baseClass)
При конкатенации строк создается новая строка. Поэтому если мы например, внутри цикла будем добавлять новые строки к текущему, то каждый раз будет создаваться новая строка.
Использовать StribgBuilder. Когда конкатенация в одну строчку, то компилятор сам заменит конкатенацию на stringBuilder и append'ы, а в случае с циклом нет скорее всего.

2017-05-24 23:23 UTC, YorovSobir commented on src/main/java/ru/spbau/mit/SimpleImplementor.java
> +        // compiler will use StringBuilder automatically
Для того чтобы оставить только уникальные методы мне надо хотя бы получить в виде строки объявление функции (без return type), а объявление от определения в нашем случае отличается лишь телом функции где только "return". Поэтому думаю, что не стоит ради этого получить сначала в виде строки объявление каждой функции  (почти тоже самое, что и каждый метод -- отдельная строка) а затем все уникальные записать в StringBuilder.

2017-05-24 23:28 UTC, YorovSobir commented on src/main/java/ru/spbau/mit/SimpleImplementor.java
> +        List<String> methods = new ArrayList<>();
У меня в конце перед записом в буфер вызывается distinct(). По времени работы это тоже самое, что и сразу тут вместо List использовать HashSet, т.к distinct скорее всего так и делает создает HashSet и добавляет в него.

2017-05-24 23:31 UTC, YorovSobir commented on src/main/java/ru/spbau/mit/SimpleImplementor.java
> +        List<String> methods = new ArrayList<>();
хотя не совсем так если учесть все эти выделения памяти.

2017-05-25 09:45 UTC, YorovSobir commented on src/main/java/ru/spbau/mit/SimpleImplementor.java
> +        List<String> methods = new ArrayList<>();
Я оставил List, поскольку когда я вызываю collect(Collectors.toMap(SimpleImplementor::methodToString,
                    Function.identity(), (p, q) -> p))
то дубликаты удалятся (mergeFunction - 3 - й параметр).

2017-05-25 09:46 UTC, YorovSobir commented on src/main/java/ru/spbau/mit/SimpleImplementor.java
> +            Arrays.stream(cur.getInterfaces())
Исправил. Заменил на getMethods.

2017-05-25 09:47 UTC, YorovSobir commented on src/main/java/ru/spbau/mit/SimpleImplementor.java
> +        // compiler will use StringBuilder automatically
Вроде исправил теперь сначала по сигнатуре функции в виде строки оставляю уникальные, а затем записываю все методы в один StringBuilder

2017-05-27 09:12 UTC, dzharkov commented
Ок, 10/10

2017-05-27 09:12 UTC, closed without merging