Java01. ДЗ 07, Клейман Вадим, подгруппа 1
java-course-au/assignments-2017-1 pull request #108
Opened 2017-05-18 19:03 UTC by VadimKleiman

2017-05-21 08:57 UTC, dzharkov requested changes
Жду исправлений и ответов на вопросы до 26.05.2017 23:59

2017-05-21 08:57 UTC, dzharkov commented on src/main/java/ru/spbau/mit/SimpleImplementor.java
> +    private static void implMethods(final StringBuilder out, final Class<?> cl, final HashSet<String> methods) {
Нельзя использовать классы-реализации в качестве типов

2017-05-21 08:57 UTC, dzharkov commented on src/main/java/ru/spbau/mit/SimpleImplementor.java
> +                tmp.append(Modifier.isPublic(cl.getModifiers()) ? "public " : "protected ");
"Повышать" visibility можно всегда

2017-05-21 08:57 UTC, dzharkov commented on src/main/java/ru/spbau/mit/SimpleImplementor.java
> +        try (BufferedWriter writer = new BufferedWriter(new FileWriter(target))) {
Можно воспользоваться FileUtils.writeStringToFile

2017-05-21 08:57 UTC, dzharkov commented on src/main/java/ru/spbau/mit/SimpleImplementor.java
> +                queue.addAll(Arrays.asList(clazz.getInterfaces()));
От обработки интерфейсов можно избавиться, воспользовавшись приятным свойством: в них все методы публичные

2017-05-26 18:54 UTC, VadimKleiman commented on src/main/java/ru/spbau/mit/SimpleImplementor.java
> +    private static void implMethods(final StringBuilder out, final Class<?> cl, final HashSet<String> methods) {
Исправил

2017-05-26 18:54 UTC, VadimKleiman commented on src/main/java/ru/spbau/mit/SimpleImplementor.java
> +                queue.addAll(Arrays.asList(clazz.getInterfaces()));
Исправил

2017-05-26 18:54 UTC, VadimKleiman commented on src/main/java/ru/spbau/mit/SimpleImplementor.java
> +        try (BufferedWriter writer = new BufferedWriter(new FileWriter(target))) {
Исправил

2017-05-27 09:17 UTC, dzharkov commented
Ок, 10/10

2017-05-27 09:17 UTC, closed without merging