Java01. ДЗ 01,Клейман Вадим, подгруппа 1
java-course-au/assignments-2017-1 pull request #12
Opened 2017-02-23 17:34 UTC by VadimKleiman

@dzharkov

2017-02-25 10:24 UTC, dzharkov requested changes
Жду исправлений и ответов на вопросы до 02.03.2017 23:59

2017-02-25 10:24 UTC, dzharkov commented on src/main/java/ru/spbau/mit/StringSetImpl.java
> +class Trie {
Этот класс правильней сделать private static внутри `StringSetImpl`, подробности расскажу на паре.

2017-02-25 10:24 UTC, dzharkov commented on src/main/java/ru/spbau/mit/StringSetImpl.java
> +    private final int size = 52;
Константы должны быть private static final

2017-02-25 10:24 UTC, dzharkov commented on src/main/java/ru/spbau/mit/StringSetImpl.java
> +    private Trie[] listRef;
Можешь пояснить название поля?

2017-02-25 10:24 UTC, dzharkov commented on src/main/java/ru/spbau/mit/StringSetImpl.java
> +        listRef = new Trie[size];
Можно убрать конструктор, а эти присвоения перенести прямо к объявлению полей

2017-02-25 10:24 UTC, dzharkov commented on src/main/java/ru/spbau/mit/StringSetImpl.java
> +    public void setTrie(Trie node, int index) {
В принципе после того, как класс `private static` геттеры/сеттеры можно убрать

2017-02-25 10:24 UTC, dzharkov commented on src/main/java/ru/spbau/mit/StringSetImpl.java
> +    private int index(char symbol) {
Этот метод может быть static + название в идеале должно быть действием

2017-02-25 10:24 UTC, dzharkov commented on src/main/java/ru/spbau/mit/StringSetImpl.java
> +                return false;
Может ли действительно возникнуть такая ситуация?

2017-02-25 10:24 UTC, dzharkov commented on src/main/java/ru/spbau/mit/StringSetImpl.java
> +        node.setTerminate(false);
Если я сначала добавлю миллион строк в бор, а затем удалю все, память не освободится,
это нужно исправить.

2017-02-25 10:24 UTC, dzharkov commented on src/main/java/ru/spbau/mit/StringSetImpl.java
> +        Trie node = head;
Здесь и в некоторых методах ниже у тебя дублируется код, который идет по дереву вниз по символам строки.
Попробуй выделить общие части **некоторых** из них в отдельный метод

2017-02-28 08:46 UTC, VadimKleiman commented on src/main/java/ru/spbau/mit/StringSetImpl.java
> +                return false;
Нет, не может. Исправил.

2017-02-28 08:47 UTC, VadimKleiman commented on src/main/java/ru/spbau/mit/StringSetImpl.java
> +    private Trie[] listRef;
Ссылки на узлы. Переименовал.

2017-02-28 08:49 UTC, VadimKleiman commented
@dzharkov, исправил

2017-03-07 06:05 UTC, dzharkov commented
Ок, 9/10

2017-03-11 08:15 UTC, closed without merging