Java01. ДЗ 06, Кольцов Михаил, подгруппа 1
java-course-au/assignments-2017-1 pull request #123
Opened 2017-05-19 14:12 UTC by ItsLastDay

2017-05-19 18:25 UTC, ItsLastDay commented
@dzharkov

2017-05-21 09:04 UTC, dzharkov requested changes

2017-05-21 09:04 UTC, dzharkov commented on src/main/java/ru/spbau/mit/SimpleImplementor.java
> +            FileWriter writer = new FileWriter(new File(dir.toString(),
Можно воспользоваться FileUtils.writeStringToFile

2017-05-21 09:04 UTC, dzharkov commented on src/main/java/ru/spbau/mit/SimpleImplementor.java
> +            for (Class<?> intrf : loadedClass.getInterfaces()) {
От обработки интерфейсов можно избавиться, воспользовавшись приятным свойством: в них все методы публичные

2017-05-21 09:04 UTC, dzharkov commented on src/main/java/ru/spbau/mit/SimpleImplementor.java
> +            Integer curHash = Arrays.hashCode(meth.getParameterTypes()) ^ meth.getName().hashCode();
Integer? коллизии?

2017-05-21 09:04 UTC, dzharkov commented on src/main/java/ru/spbau/mit/SimpleImplementor.java
> +        for (Class<?> arg : meth.getParameterTypes()) {
Ну почему же вы не используете стримы :(

2017-05-21 09:04 UTC, dzharkov commented
Жду исправлений и ответов на вопросы до 26.05.2017 23:59

2017-05-23 11:33 UTC, ItsLastDay commented
@dzharkov 
-Воспользовался writeStringToFile;
-убрал обработку интерфейсов - заменил на вызов getMethods;
-фильтрую методы теперь так: создаю строку вида <имя метода;;;тип параметра1;;; тип параметра2...>, по ним оставляю уникальные методы. Хотелось сделать это с помощью стримов (т.е. выкинув HashSet), нагуглил одно из возможных решений;
-использую стримы и Collectors.joining вместо некоторых циклов.

2017-05-27 09:15 UTC, dzharkov commented
Ок, 10/10

2017-05-27 09:15 UTC, closed without merging