Java01. ДЗ 07, Симиютин Борис, подгруппа 1
java-course-au/assignments-2017-1 pull request #124
Opened 2017-05-19 18:56 UTC by simiyutin

2017-05-21 09:11 UTC, dzharkov requested changes
Жду исправлений и ответов на вопросы до 26.05.2017 23:59

2017-05-21 09:11 UTC, dzharkov commented on src/main/java/ru/spbau/mit/SimpleImplementor.java
> +            Integer curHash = Arrays.hashCode(m.getParameterTypes()) ^ m.getName().hashCode();
Докажи, что не списывал :-1: 
https://github.com/java-course-au/assignments-2017-1/pull/123/files#diff-b80a0d06d8f19186ece0880be5393bfeR121

2017-05-21 09:11 UTC, dzharkov commented on src/main/java/ru/spbau/mit/SimpleImplementor.java
> +        for (Class interf : cls.getInterfaces()) {
От обработки интерфейсов можно избавиться, воспользовавшись приятным свойством: в них все методы публичные

2017-05-21 09:11 UTC, dzharkov commented on src/main/java/ru/spbau/mit/SimpleImplementor.java
> +        } else if (Modifier.isPrivate(mod)) {
А это кстати норм, что мы перекрываем приватные/статичные и final методы?

2017-05-21 09:11 UTC, dzharkov commented on src/main/java/ru/spbau/mit/SimpleImplementor.java
> +    private int varNameInd = 0;
Не очень правильно хранить это как состояние в `SimpleImplementor`
Как минимум класс становится не thread-safe, хотя по идее предпосылок к этому нет.

2017-05-26 16:38 UTC, simiyutin commented on src/main/java/ru/spbau/mit/SimpleImplementor.java
> +            Integer curHash = Arrays.hashCode(m.getParameterTypes()) ^ m.getName().hashCode();
Идею с хешем я правда подсмотрел. Но то что эту фильтрацию надо делать я не подсматривал, а понял по логу этого билда. https://semaphoreci.com/dzharkov/assignments-2017-1/branches/pull-request-124/builds/7 . Заглянул в чужое решение, потому что сначала пришло в голову формировать строковое представление сигнатуры метода и искать его в сете, но побоялся напороться на новые ошибки и не успеть к дедлайну.

2017-05-26 17:22 UTC, simiyutin commented on src/main/java/ru/spbau/mit/SimpleImplementor.java
> +        } else if (Modifier.isPrivate(mod)) {
Не норм, но этот кусок не создавал проблемы, так как я выше фильтрую методы по isAbstract, а если метод родителя  одновременно abstract и private / static / final, то будет ошибка компиляции.

2017-05-27 09:19 UTC, dzharkov commented on src/main/java/ru/spbau/mit/SimpleImplementor.java
> +            Integer curHash = Arrays.hashCode(m.getParameterTypes()) ^ m.getName().hashCode();
Надо было уж там посмотреть и замечение к этому коду))
-1

2017-05-27 09:19 UTC, dzharkov commented
Ок, 9/10

2017-05-27 09:19 UTC, closed without merging