Java01. ДЗ 2. Малютина Катя, подгруппа 2.
java-course-au/assignments-2017-1 pull request #18
Opened 2017-03-06 21:43 UTC by ekaterinaMaljutina

@sproshev

2017-03-11 20:13 UTC, sproshev requested changes
надо исправлять

2017-03-11 20:13 UTC, sproshev commented on hw2_malyutina/src/main/java/ru/spbau/mit/DictionaryImpl.java
> +    private int sizeTable = TABLE_SIZE;
верно ли, что sizeTable всегда равен table.length?

2017-03-11 20:13 UTC, sproshev commented on hw2_malyutina/src/main/java/ru/spbau/mit/DictionaryImpl.java
> +    private int sizeNotEmptyElem = 0;
может просто size?

2017-03-11 20:13 UTC, sproshev commented on hw2_malyutina/src/main/java/ru/spbau/mit/DictionaryImpl.java
> +    }
приватные методы внизу

2017-03-11 20:13 UTC, sproshev commented on hw2_malyutina/src/main/java/ru/spbau/mit/DictionaryImpl.java
> +        sizeNotEmptyElem = sizeNotEmptyElem + 1;
size++;

2017-03-11 20:13 UTC, sproshev commented on hw2_malyutina/src/test/java/DictionaryTest.java
> +
```
    @Test
    public void testAbc() {
        final DictionaryImpl dictionary = new DictionaryImpl();
        dictionary.put("k", "v");
        assertEquals(1, dictionary.size());
        dictionary.put("k", "v1");
        assertEquals(1, dictionary.size());
    }
```

падает

2017-03-11 20:13 UTC, sproshev commented on hw2_malyutina/src/main/java/ru/spbau/mit/DictionaryImpl.java
> +    public String get(@NotNull String key) {
если уж использовать аннотации, то и на возвращаемых значениях тоже

2017-03-11 20:13 UTC, sproshev commented on hw2_malyutina/src/main/java/ru/spbau/mit/DictionaryImpl.java
> +        sizeNotEmptyElem = sizeNotEmptyElem - 1;
size--;

2017-03-11 20:13 UTC, sproshev commented on hw2_malyutina/src/main/java/ru/spbau/mit/DictionaryImpl.java
> +                current = oldLists[i].getNode();
со стороны эта строка и строка выше (`Node current = oldLists[i].getNode();`) приводят к ощущению, что здесь все зацикливается

надо написать, чтобы было понятно происходящее

2017-03-11 20:13 UTC, sproshev commented on hw2_malyutina/src/main/java/ru/spbau/mit/DictionaryImpl.java
> +        for (int i = 0; i < sizeTable; i++) {
sizeTable то может сбросить тогда? зачем оставлять тот же?

2017-03-11 20:13 UTC, sproshev commented on hw2_malyutina/src/main/java/ru/spbau/mit/DictionaryImpl.java
> +    private class LinkedList {
static

2017-03-11 20:13 UTC, sproshev commented on hw2_malyutina/src/main/java/ru/spbau/mit/DictionaryImpl.java
> +        LinkedList(@NotNull String key, @NotNull String value) {
unused

2017-03-11 20:13 UTC, sproshev commented on hw2_malyutina/src/main/java/ru/spbau/mit/DictionaryImpl.java
> +        private String valueNode;
просто key, value?

2017-03-11 20:13 UTC, sproshev commented on hw2_malyutina/src/main/java/ru/spbau/mit/DictionaryImpl.java
> +        Node() {
unused

2017-03-11 20:13 UTC, sproshev commented on hw2_malyutina/src/main/java/ru/spbau/mit/DictionaryImpl.java
> +        table[index].insert(key, value);
за одно обращение к списку можно и нужно сделать

2017-03-11 20:41 UTC, ekaterinaMaljutina commented on hw2_malyutina/src/main/java/ru/spbau/mit/DictionaryImpl.java
> +    private int sizeTable = TABLE_SIZE;
нет, только на начальный момент. Как только мы сделали перехеширование, то sizeTable изменилось.

2017-03-11 20:44 UTC, sproshev commented on hw2_malyutina/src/main/java/ru/spbau/mit/DictionaryImpl.java
> +    private int sizeTable = TABLE_SIZE;
и после создания table c новым sizeTable, стало равным table.length:

```
        sizeTable = sizeTable * EXPANDING_SIZE;
        table = new LinkedList[sizeTable];
```

2017-03-12 07:46 UTC, ekaterinaMaljutina commented
@sproshev Поправила

2017-03-18 22:50 UTC, sproshev approved these changes
9, -0.5 за тест, -0.5 за clear

2017-03-18 22:50 UTC, sproshev commented on hw2_malyutina/src/main/java/ru/spbau/mit/DictionaryImpl.java
> +        for (int i = 0; i < TABLE_SIZE; i++) {
после TABLE_SIZE тоже жизнь может быть...

2017-03-18 22:50 UTC, sproshev commented on hw2_malyutina/src/main/java/ru/spbau/mit/DictionaryImpl.java
> +        for (int i = 0; i < oldLists.length; i++) {
см for-each

2017-03-18 22:50 UTC, sproshev commented on hw2_malyutina/src/main/java/ru/spbau/mit/DictionaryImpl.java
> +                    oldValue = currentNode.value;
oldValue по сути используется только здесь, в остальных местах оно всегда null

2017-03-18 22:50 UTC, sproshev commented on hw2_malyutina/src/main/java/ru/spbau/mit/DictionaryImpl.java
> +            String oldValue = null;
здесь аналогично

2017-03-18 22:50 UTC, sproshev commented on hw2_malyutina/src/main/java/ru/spbau/mit/DictionaryImpl.java
> +        private String key;
final

2017-03-19 15:56 UTC, closed without merging