Java01. ДЗ 02, Кручинин Дмитрий, подгруппа 1
java-course-au/assignments-2017-1 pull request #19
Opened 2017-03-07 10:24 UTC by KruchDmitriy

2017-03-11 09:23 UTC, dzharkov requested changes
Жду исправлений и ответов на вопросы до 17/03 23:59

2017-03-11 09:23 UTC, dzharkov commented on src/main/java/ru/spbau/mit/DictionaryImpl.java
> +    private int getNumberOfBucket(String key) {
Кажется, что метод должен вернуть количество чего-то

2017-03-11 09:23 UTC, dzharkov commented on src/main/java/ru/spbau/mit/DictionaryImpl.java
> +            if (bucket.getSize() == BUCKET_SIZE) {
Эта стратегия мне очень не нравится.
Если добавить в словарь `BUCKET_SIZE+1` строк с одинаковым хэш-кодом, то все сломается?

2017-03-11 09:23 UTC, dzharkov commented on src/main/java/ru/spbau/mit/DictionaryImpl.java
> +            if (bucket.getSize() == BUCKET_SIZE) {
-1

2017-03-11 09:23 UTC, dzharkov commented on src/main/java/ru/spbau/mit/DictionaryImpl.java
> +            size = 0;
Можно убрать конструктор, а эти присвоения перенести прямо к объявлению полей

2017-03-11 09:23 UTC, dzharkov commented on src/main/java/ru/spbau/mit/DictionaryImpl.java
> +        int getSize() {
Эти методы могут быть private, -1

2017-03-11 09:23 UTC, dzharkov commented on src/main/java/ru/spbau/mit/DictionaryImpl.java
> +            for (int i = 0; i < size; i++) {
Некоторые методы ниже содержат много общего кода

2017-03-11 09:23 UTC, dzharkov commented on src/main/java/ru/spbau/mit/DictionaryImpl.java
> +    private class ArrayDict {
private static?

2017-03-11 14:58 UTC, KruchDmitriy commented on src/main/java/ru/spbau/mit/DictionaryImpl.java
> +            if (bucket.getSize() == BUCKET_SIZE) {
Если у строк будет одинаковый hashCode(), то, конечно, да. Здесь идея состояла в том, чтобы жестко ограничить сверху константу на поиск элемента. Если считать, что hashCode() выдаёт нам равномерное распределение (на отрезке [0, 2^32 - 1]), то можно показать (математически), что разницы между увеличением bucket_size, и size никакой. Я конечно переборщил указав там 10. Однако, поскольку, на алгоритмах мне ничего ещё не рассказывали про хеш-таблицы, и на паре не было никаких указаний на то, как это делать (вернее, вообще было сказано, что не надо делать рехэш), то я исходил из рассуждений с точки зрения теории вероятностей. Надеюсь, я ответил на вопрос =).

2017-03-11 14:58 UTC, KruchDmitriy commented on src/main/java/ru/spbau/mit/DictionaryImpl.java
> +    private class ArrayDict {
О, круто), спасибо.

2017-03-18 07:01 UTC, dzharkov commented
Ок, 8/10

2017-03-18 07:01 UTC, closed without merging