Java01. ДЗ 01, Гардер Антон, подгруппа 1
java-course-au/assignments-2017-1 pull request #2
Opened 2017-02-17 08:05 UTC by avgarder

@dzharkov

2017-02-25 08:22 UTC, dzharkov requested changes
Жду исправлений и ответов на вопросы до 02.03.2017 23:59

2017-02-25 08:22 UTC, dzharkov commented on src/main/java/ru/spbau/mit/StringSetImpl.java
> +    private int charToIdx(char c) {
1. Может быть статическим
2. В общем случае не рекомендуется использовать сокращения вроде `idx/res`
3. Если быть совсем занудой, то методы в джаве должны начинаться с глагола

2017-02-25 08:22 UTC, dzharkov commented on src/main/java/ru/spbau/mit/StringSetImpl.java
> +        if (idx == s.length()) {
Здесь и в некоторых методах ниже у тебя дублируется код, который идет по дереву вниз по символам строки.
Попробуй выделить общие части **некоторых** из них в отдельный метод

2017-02-25 08:22 UTC, dzharkov commented on src/main/java/ru/spbau/mit/StringSetImpl.java
> +        boolean res = add(next, s, idx + 1);
В чем минус рекурсивного подхода перед нерекурсивным?
Можешь избавиться от рекурсии?

2017-02-25 08:22 UTC, dzharkov commented on src/main/java/ru/spbau/mit/StringSetImpl.java
> +        private Node[] child = new Node[ALPHABET_SIZE];
Правильней было бы назвать массив `children`

2017-02-26 07:38 UTC, avgarder commented on src/main/java/ru/spbau/mit/StringSetImpl.java
> +        boolean res = add(next, s, idx + 1);
Минус рекурсивного подхода в том, что он требует больше памяти на стек и работает медленнее.

2017-02-26 07:44 UTC, avgarder commented
@dzharkov

2017-03-07 05:31 UTC, dzharkov commented
Ок

2017-03-07 05:31 UTC, closed without merging