Java01. ДЗ 2, Симиютин Борис, подгруппа 2
java-course-au/assignments-2017-1 pull request #20
Opened 2017-03-07 16:28 UTC by simiyutin

2017-03-07 20:55 UTC, simiyutin commented
@sproshev

2017-03-10 08:21 UTC, sproshev commented
Перевод к @dzharkov

2017-03-10 08:35 UTC, sproshev commented
Чтобы Денис проверил, надо заменить "подгруппа 2" на "подгруппа 1"

2017-03-11 10:53 UTC, dzharkov approved these changes
Жду исправлений и ответов на вопросы до 17/03 23:59

2017-03-11 10:53 UTC, dzharkov commented on src/main/java/ru/spbau/mit/DictionaryImpl.java
> +
Просто интересно, зачем в начале каждого метода пустая строка?

2017-03-11 10:53 UTC, dzharkov commented on src/main/java/ru/spbau/mit/DictionaryImpl.java
> +        if (contains(key)) {
Зачем эта проверка здесь?

2017-03-11 10:53 UTC, dzharkov commented on src/main/java/ru/spbau/mit/DictionaryImpl.java
> +        if (contains(key)) {
Можешь переписать метод, чтобы не было этой проверки?
То есть, оставить один проход по бакету

2017-03-11 10:53 UTC, dzharkov commented on src/main/java/ru/spbau/mit/DictionaryImpl.java
> +    private int getHash(String key) {
Это все-таки не совсем `getHash`

2017-03-11 10:53 UTC, dzharkov commented on src/main/java/ru/spbau/mit/DictionaryImpl.java
> +            return getBucket(key).remove(key);
Нужно не забывать отслеживать ситуацию, что если много бакетов пустые, то нужно уменьшить их количество

2017-03-11 10:53 UTC, dzharkov commented on src/main/java/ru/spbau/mit/DictionaryImpl.java
> +        class Node {
private static

2017-03-11 10:53 UTC, dzharkov commented on src/main/java/ru/spbau/mit/DictionaryImpl.java
> +        void push(String key, String value) {
Все эти методы должны быть private

2017-03-11 13:44 UTC, simiyutin commented on src/main/java/ru/spbau/mit/DictionaryImpl.java
> +
Мне легче читать, когда сигнатура отделена от реализации :)

2017-03-11 13:44 UTC, simiyutin commented on src/main/java/ru/spbau/mit/DictionaryImpl.java
> +        if (contains(key)) {
removed

2017-03-11 13:44 UTC, simiyutin commented on src/main/java/ru/spbau/mit/DictionaryImpl.java
> +        if (contains(key)) {
fixed

2017-03-11 13:45 UTC, simiyutin commented on src/main/java/ru/spbau/mit/DictionaryImpl.java
> +            return getBucket(key).remove(key);
fixed

2017-03-11 13:45 UTC, simiyutin commented on src/main/java/ru/spbau/mit/DictionaryImpl.java
> +    private int getHash(String key) {
getHash -> getIndex

2017-03-11 13:45 UTC, simiyutin commented on src/main/java/ru/spbau/mit/DictionaryImpl.java
> +        void push(String key, String value) {
fixed

2017-03-11 13:45 UTC, simiyutin commented on src/main/java/ru/spbau/mit/DictionaryImpl.java
> +        class Node {
fixed

2017-03-11 13:47 UTC, simiyutin commented
@dzharkov

2017-03-11 15:22 UTC, dzharkov requested changes

2017-03-11 15:22 UTC, dzharkov commented on src/main/java/ru/spbau/mit/DictionaryImpl.java
> +
Стандартные соглашения не очень жалуют такой подход
https://google.github.io/styleguide/javaguide.html 4.6
Так что предлагаю от них избавиться, также как и от пустой строки в начале класса

2017-03-11 16:01 UTC, simiyutin commented
@dzharkov Кстати, вопрос. Нужно ли каждый раз после исправлений повторять этот коммент, или нет?

2017-03-18 07:06 UTC, dzharkov requested changes
Жду исправлений и ответов на вопросы до 24/03 23:59

2017-03-18 07:06 UTC, dzharkov commented on src/main/java/ru/spbau/mit/DictionaryImpl.java
> +        List.Node node = bucket.remove(key);
Получается, что если я сначала добавил много ключей, а потом их все удалил, то количество бакетов не изменится? -1

2017-03-18 14:46 UTC, simiyutin commented on src/main/java/ru/spbau/mit/DictionaryImpl.java
> +        List.Node node = bucket.remove(key);
Поправил

2017-03-18 15:19 UTC, simiyutin commented
@dzharkov

2017-03-25 14:14 UTC, dzharkov commented
Ок, 9/10

2017-03-25 14:14 UTC, closed without merging