init commit
java-course-au/assignments-2017-1 pull request #21
Opened 2017-03-07 21:19 UTC by VadimKleiman

@dzharkov

2017-03-11 09:43 UTC, dzharkov requested changes
Жду исправлений и ответов на вопросы до 17/03 23:59

2017-03-11 09:43 UTC, dzharkov commented on src/main/java/ru/spbau/mit/DictionaryImpl.java
> +    private class Array {
Очень плохое название класса. Массивы в джаве уже есть и они обозначаются, как `String[]`

2017-03-11 09:43 UTC, dzharkov commented on src/main/java/ru/spbau/mit/DictionaryImpl.java
> +            rehash();
А что, если будет много элементов с одинаковым хэш-кодом?

2017-03-11 09:43 UTC, dzharkov commented on src/main/java/ru/spbau/mit/DictionaryImpl.java
> +        return hashMap[hash].remove(key);
Кстати, нужно не забывать отслеживать ситуацию, что если много бакетов пустые, то нужно уменьшить их количество

2017-03-11 09:43 UTC, dzharkov commented on src/main/java/ru/spbau/mit/DictionaryImpl.java
> +    private static final int START_SIZE = 32;
Вообще очень неприятно читать решение, до боли похожее на https://github.com/java-course-au/assignments-2017-1/pull/19/files

2017-03-11 09:43 UTC, dzharkov commented on src/main/java/ru/spbau/mit/DictionaryImpl.java
> +        int hash = Math.abs(key.hashCode()) % sizeMap;
Ну вот это выражение `Math.abs(key.hashCode()) % sizeMap` еще в тысяче мест встречается, -1

2017-03-11 09:43 UTC, dzharkov commented on src/main/java/ru/spbau/mit/DictionaryImpl.java
> +            rehash();
-1

2017-03-11 09:43 UTC, dzharkov commented on src/main/java/ru/spbau/mit/DictionaryImpl.java
> +            for (int i = 0; i < SIZE; i++) {
Дублирование кода здесь и ниже, -1

2017-03-11 09:43 UTC, dzharkov commented on src/main/java/ru/spbau/mit/DictionaryImpl.java
> +        private class Node {
private static

2017-03-11 13:16 UTC, VadimKleiman commented on src/main/java/ru/spbau/mit/DictionaryImpl.java
> +            rehash();
Всё сломается. Бесконечный вызов метода rehash()
Переписал. Теперь всё должно быть хорошо.

2017-03-11 13:17 UTC, VadimKleiman commented on src/main/java/ru/spbau/mit/DictionaryImpl.java
> +        int hash = Math.abs(key.hashCode()) % sizeMap;
Исправил.

2017-03-11 13:17 UTC, VadimKleiman commented on src/main/java/ru/spbau/mit/DictionaryImpl.java
> +        return hashMap[hash].remove(key);
Исправил.

2017-03-11 13:18 UTC, VadimKleiman commented on src/main/java/ru/spbau/mit/DictionaryImpl.java
> +    private class Array {
Согласен. Переименовал.

2017-03-11 13:18 UTC, VadimKleiman commented on src/main/java/ru/spbau/mit/DictionaryImpl.java
> +            for (int i = 0; i < SIZE; i++) {
Исправил

2017-03-11 13:18 UTC, VadimKleiman commented on src/main/java/ru/spbau/mit/DictionaryImpl.java
> +        private class Node {
Исправил

2017-03-11 13:36 UTC, VadimKleiman commented on src/main/java/ru/spbau/mit/DictionaryImpl.java
> +    private static final int START_SIZE = 32;
В прошлом семестре нам читали курс по базам данных, на котором рассказали идею с фиксированным размером корзины. Как следствие похожие решения.

2017-03-18 07:10 UTC, dzharkov commented
Ок, 7/10

2017-03-18 07:10 UTC, closed without merging