Java01. ДЗ 02, Ёров Собир, подгруппа 1
java-course-au/assignments-2017-1 pull request #22
Opened 2017-03-08 14:34 UTC by YorovSobir

@dzharkov

2017-03-11 10:32 UTC, dzharkov requested changes
Жду исправлений и ответов на вопросы до 17/03 23:59

2017-03-11 10:32 UTC, dzharkov commented on src/main/java/ru/spbau/mit/DictionaryImpl.java
> +    private static final class List {
Этот класс правильней было бы назвать `ListNode`

2017-03-11 10:32 UTC, dzharkov commented on src/main/java/ru/spbau/mit/DictionaryImpl.java
> +        if (pred == cur) {
Кстати, нужно не забывать отслеживать ситуацию, что если много бакетов пустые, то нужно уменьшить их количество

2017-03-11 10:32 UTC, dzharkov commented on src/main/java/ru/spbau/mit/DictionaryImpl.java
> +            clear(cur.next);
Здесь точно нужна рекурсия?

2017-03-11 10:32 UTC, dzharkov commented on src/main/java/ru/spbau/mit/DictionaryImpl.java
> +    private int getHashCode(String key) {
Правильней назвать это `getBucketId`

2017-03-11 10:32 UTC, dzharkov commented on src/main/java/ru/spbau/mit/DictionaryImpl.java
> +            if (pred == cur) {
Этот метод, в целом, не очень аккуратно написан.
Можешь прокомментировать, почему эти действия лишние?

2017-03-11 10:32 UTC, dzharkov commented on src/main/java/ru/spbau/mit/DictionaryImpl.java
> +        List pred = cur;
Правильней было бы сказать, что `pred = null`

2017-03-11 10:32 UTC, dzharkov commented on src/main/java/ru/spbau/mit/DictionaryImpl.java
> +        if (contains(key)) {
Можешь попробовать переписать метод, чтобы не нужно было проверять, есть ли такой ключ или нет?

2017-03-11 11:22 UTC, YorovSobir commented on src/main/java/ru/spbau/mit/DictionaryImpl.java
> +            if (pred == cur) {
Да действительно, эти блоки if и else ничего полезного не делают. Они еще раз присваивают значения, которые и так были присвоены раньше. 
1. if (pred == cur) т.е не зашли в цикл (который чуть выше). Следовательно cur = hashTable[hash]. А внутри if я делаю hashTable[hash] = cur, что бессмысленно.
2. else {pred.next = cur} - т.е мы зашли в цикл и вышли когда нашли ListNode. Но pred.next и так равняется cur, а я еще раз присвоил. 
Извините за это г..нокод).

2017-03-11 11:22 UTC, YorovSobir commented on src/main/java/ru/spbau/mit/DictionaryImpl.java
> +    private static final class List {
Исправил

2017-03-11 11:23 UTC, YorovSobir commented on src/main/java/ru/spbau/mit/DictionaryImpl.java
> +        List pred = cur;
Исправил

2017-03-11 11:26 UTC, YorovSobir commented on src/main/java/ru/spbau/mit/DictionaryImpl.java
> +        if (contains(key)) {
Переписал. Получилось намного понятнее. Спасибо.

2017-03-11 11:35 UTC, YorovSobir commented on src/main/java/ru/spbau/mit/DictionaryImpl.java
> +    private int getHashCode(String key) {
Исправил

2017-03-11 11:46 UTC, YorovSobir commented on src/main/java/ru/spbau/mit/DictionaryImpl.java
> +            clear(cur.next);
Можно и без рекурсии. Написал по привычке через рекурсию. Исправил.

2017-03-11 13:22 UTC, YorovSobir commented on src/main/java/ru/spbau/mit/DictionaryImpl.java
> +        if (pred == cur) {
Исправил

2017-03-11 13:23 UTC, YorovSobir commented
@dzharkov

2017-03-11 13:32 UTC, YorovSobir commented
@dzharkov

2017-03-18 07:15 UTC, dzharkov commented
Ок, 10/10

2017-03-18 07:15 UTC, closed without merging