Java01. ДЗ 02, Кольцов Михаил, подгруппа 1
java-course-au/assignments-2017-1 pull request #23
Opened 2017-03-08 21:03 UTC by ItsLastDay

2017-03-08 21:07 UTC, ItsLastDay commented
@dzharkov

2017-03-11 10:37 UTC, dzharkov requested changes
Жду исправлений и ответов на вопросы до 17/03 23:59

2017-03-11 10:37 UTC, dzharkov commented on src/main/java/ru/spbau/mit/DictionaryImpl.java
> +        return containedValue;
Нужно не забывать отслеживать ситуацию, что если много бакетов пустые, то нужно уменьшить их количество

2017-03-11 10:37 UTC, dzharkov commented on src/main/java/ru/spbau/mit/DictionaryImpl.java
> +    private int findBucketIndex(String key, int numBuckets) {
static?

2017-03-11 10:37 UTC, dzharkov commented on src/main/java/ru/spbau/mit/DictionaryImpl.java
> +        public static StringListNode removeByKey(StringListNode head, String key) {
Неоптимальная visibility у методов, -1

2017-03-11 10:37 UTC, dzharkov commented on src/main/java/ru/spbau/mit/DictionaryImpl.java
> +            head.setNextNode(StringListNode.removeByKey(nextNode, key));
Лучше не использовать в таких случаях рекурсию

2017-03-13 20:31 UTC, ItsLastDay commented
@dzharkov 
Поменял рекурсию на циклы при обработке списка;
Внутри класса списка изменил visibility на default;
Сделал указанный метод статическим.

2017-03-17 08:08 UTC, ItsLastDay commented
Сделал все методы внутреннего класса private. После этого checkstyle сказал, что внутренний класс должен быть final - сделал так.

2017-03-18 07:17 UTC, dzharkov commented
Ок, 9/10

2017-03-18 07:17 UTC, closed without merging