Java01. ДЗ 03, Гардер Антон, подгруппа 1
java-course-au/assignments-2017-1 pull request #27
Opened 2017-03-10 08:44 UTC by avgarder

@dzharkov

2017-03-18 07:57 UTC, dzharkov requested changes
Жду исправлений и ответов на вопросы до 24/03 23:59

2017-03-18 07:57 UTC, dzharkov commented on src/main/java/ru/spbau/mit/StringSetImpl.java
> +        PrintWriter pw = new PrintWriter(out);
Как я говорил на паре, `PrintWriter/Reader` удобны для взамодействия с текстовыми (понятными человеку) данными.
Для сериализации я предлагал использовать другие реализации

2017-03-18 07:57 UTC, dzharkov commented on src/main/java/ru/spbau/mit/StringSetImpl.java
> +        PrintWriter pw = new PrintWriter(out);
И прокомментируй, кстати, в чем недостатки использования PrintWriter

2017-03-18 07:59 UTC, dzharkov commented on src/main/java/ru/spbau/mit/StringSetImpl.java
> +        pw.println(n.terminalsNumber);
Является ли это избыточной информацией для сериализации?

2017-03-20 15:05 UTC, avgarder commented on src/main/java/ru/spbau/mit/StringSetImpl.java
> +        PrintWriter pw = new PrintWriter(out);
Недостатки PrintWriter: менее эффективен из-за того, что преобразует всё в строки; подавляет исключения.

2017-03-20 15:05 UTC, avgarder commented on src/main/java/ru/spbau/mit/StringSetImpl.java
> +        pw.println(n.terminalsNumber);
Да, но зато позволяет не тратить время на обход десериализованной структуры.

2017-03-20 15:06 UTC, avgarder commented
@dzharkov

2017-03-25 14:16 UTC, dzharkov commented on src/main/java/ru/spbau/mit/StringSetImpl.java
> +        pw.println(n.terminalsNumber);
На самом деле нет, ты просто можешь в ходе десериализации суммировать результаты детей.
В принципе некритично

2017-03-25 14:17 UTC, dzharkov commented
Ок, 10/10

2017-03-25 14:17 UTC, closed without merging