Java01. ДЗ 03, Симиютин Борис, подгруппа 1
java-course-au/assignments-2017-1 pull request #35
Opened 2017-03-14 18:45 UTC by simiyutin

2017-03-16 09:59 UTC, simiyutin commented
@dzharkov

2017-03-18 08:03 UTC, dzharkov requested changes
Жду исправлений и ответов на вопросы до 24/03 23:59

2017-03-18 08:03 UTC, dzharkov commented on src/main/java/ru/spbau/mit/StringSetImpl.java
> +        str.writeInt(node.howManyStartsWithPrefix);
Кажется, что это совершенно лишняя информация в рамках сериализации

2017-03-18 15:06 UTC, simiyutin commented
@dzharkov

2017-03-25 14:20 UTC, dzharkov commented
Ок, 10/10

2017-03-25 14:20 UTC, closed without merging