Java01. ДЗ 01, Лапицкая Людмила, подгруппа 1
java-course-au/assignments-2017-1 pull request #4
Opened 2017-02-20 21:40 UTC by bugogish

@dzharkov

2017-02-25 08:44 UTC, dzharkov requested changes
Жду исправлений и ответов на вопросы до 02.03.2017 23:59

2017-02-25 08:44 UTC, dzharkov commented on src/main/java/ru/spbau/mit/StringSetImpl.java
> +class Trie {
Если честно, я не очень понял, зачем выносить логику самого бора в отдельный класс.
Как минимум я бы сделал его private static внутри `StringSetImpl`, если не ожидается, что он может быть использовал снаружи.

2017-02-25 08:44 UTC, dzharkov commented on src/main/java/ru/spbau/mit/StringSetImpl.java
> +class Trie {
Вообще на будущее, разные top-level классы обычно разносят по разным файлам.
Как минимум для избежания проблем с тем, что в некоторых случаях компилятор может не найти несколько классов в одном файле.

2017-02-25 08:44 UTC, dzharkov commented on src/main/java/ru/spbau/mit/StringSetImpl.java
> +    private char symbol;
Так как это поле используется только для методов, которые по сути никто не использует, я бы попросил от него избавиться

2017-02-25 08:44 UTC, dzharkov commented on src/main/java/ru/spbau/mit/StringSetImpl.java
> +    @Override
Зачем здесь переопределены `equals`/`hashCode`?

2017-02-25 08:44 UTC, dzharkov commented on src/main/java/ru/spbau/mit/StringSetImpl.java
> +        int next = children.indexOf(new Trie(element.charAt(index)));
Видимо, это очень противоестественный способ хранения детей в боре, что нам приходится таким образом (за линию) искать ребенка по символу

2017-02-25 08:44 UTC, dzharkov commented on src/main/java/ru/spbau/mit/StringSetImpl.java
> +        if (index == element.length()) {
Здесь и в некоторых методах ниже у тебя дублируется код, который идет по дереву вниз по символам строки.
Попробуй выделить общие части **некоторых** из них в отдельный метод

2017-02-25 08:44 UTC, dzharkov commented on src/main/java/ru/spbau/mit/StringSetImpl.java
> +        boolean added = children.get(next).add(element, index + 1);
В чем минус рекурсивного подхода перед нерекурсивным?
Можешь избавиться от рекурсии?

2017-03-07 05:46 UTC, dzharkov requested changes
Жду исправлений и ответов на вопросы до 10.03.2017 23:59

2017-03-07 05:46 UTC, dzharkov commented on src/main/java/ru/spbau/mit/StringSetImpl.java
> +        Trie() {
Можно убрать конструктор, а эти присвоение перенести прямо к объявлению поля

2017-03-07 05:46 UTC, dzharkov commented on src/main/java/ru/spbau/mit/StringSetImpl.java
> +        private int charToIndex(char symbol) {
Метод может быть private static

2017-03-07 05:46 UTC, dzharkov commented on src/main/java/ru/spbau/mit/StringSetImpl.java
> +        private int charToIndex(char symbol) {
Вообще мне не очень ясно, зачем эти методы внутри этого класса.
Произошла как будто некоторая путаница: поля класса говорят, что объекты этого класса - это вершины бора, при этом название класса `Trie`, и у него есть методы `add/..`.
Сразу скажу, что private полня внутреннего класса доступны из внешнего

2017-03-07 05:46 UTC, dzharkov commented on src/main/java/ru/spbau/mit/StringSetImpl.java
> +            if (!contains(element)) {
Обычно, если ветка *else* условия состоит из оператора return, то условие инвертируют. Так код читать проще, к тому же уменьшатся вложенность отступов в содержательной части.

2017-03-07 05:46 UTC, dzharkov commented on src/main/java/ru/spbau/mit/StringSetImpl.java
> +                while (index != element.length()) {
Кажется, ты проигнорировала комментарий про попытку избавиться от повторений, -1

2017-03-07 11:26 UTC, bugogish commented on src/main/java/ru/spbau/mit/StringSetImpl.java
> +                while (index != element.length()) {
@dzharkov Я не игнорировала Ваш комментарий и добавила функцию find, чтобы избавиться от дублирования кода в функциях contains и howManyStartsWithPref.
В add и remove её использовать не получилось из-за особенной логики изменения дерева (во время обхода нужно делать специфические вещи).
Подскажите, как можно исправить эту часть моего решения?

2017-03-07 20:17 UTC, bugogish commented on src/main/java/ru/spbau/mit/StringSetImpl.java
> +        Trie() {
@dzharkov Это замечание уже было исправлено к последнему коммиту до дедлайна.

2017-03-07 20:17 UTC, bugogish commented on src/main/java/ru/spbau/mit/StringSetImpl.java
> +            if (!contains(element)) {
@dzharkov Это замечание уже было исправлено к последнему коммиту до дедлайна.

2017-03-07 20:19 UTC, bugogish commented on src/main/java/ru/spbau/mit/StringSetImpl.java
> +                while (index != element.length()) {
@dzharkov *Исправила в пятом коммите, а Вы делали ревью к третьему.

2017-03-18 07:45 UTC, dzharkov commented
Ок, 10/10

2017-03-18 07:45 UTC, closed without merging