Java01. ДЗ 03, Клейман Вадим, подгруппа 1
java-course-au/assignments-2017-1 pull request #40
Opened 2017-03-15 21:25 UTC by VadimKleiman

@dzharkov

2017-03-18 08:17 UTC, dzharkov requested changes
Жду исправлений и ответов на вопросы до 24/03 23:59

2017-03-18 08:17 UTC, dzharkov commented on src/main/java/ru/spbau/mit/StringSetImpl.java
> +            out.write(node.howManyStartsWithPrefix);
Кажется, что это совершенно лишняя информация в рамках сериализации

2017-03-18 08:17 UTC, dzharkov commented on src/main/java/ru/spbau/mit/StringSetImpl.java
> +        out.write(symbol);
И это, вроде бы тоже, лишнее.
Ты все равно перечисляешь всех детей, так что и так ясно, какой перед нами символ

2017-03-18 08:17 UTC, dzharkov commented on src/main/java/ru/spbau/mit/StringSetImpl.java
> +        node.isTerminated = in.read() == TRUE_MARKER;
Вот здесь ты как раз переизобретаешь немножко те, структуры данных, которые я рекомендовал использовать

2017-03-18 08:17 UTC, dzharkov commented on src/main/java/ru/spbau/mit/StringSetImpl.java
> +                readNode(in, root);
Или вот ROOT_MARKER. И так ведь понятно, что первая вершина и будет корнем

2017-03-21 16:44 UTC, VadimKleiman commented on src/main/java/ru/spbau/mit/StringSetImpl.java
> +            out.write(node.howManyStartsWithPrefix);
Исправил

2017-03-21 16:45 UTC, VadimKleiman commented on src/main/java/ru/spbau/mit/StringSetImpl.java
> +        out.write(symbol);
Переделал. Теперь храню только ненулевые узлы

2017-03-21 16:45 UTC, VadimKleiman commented on src/main/java/ru/spbau/mit/StringSetImpl.java
> +        node.isTerminated = in.read() == TRUE_MARKER;
Исправил

2017-03-21 16:46 UTC, VadimKleiman commented on src/main/java/ru/spbau/mit/StringSetImpl.java
> +                readNode(in, root);
Исправил

2017-03-21 17:10 UTC, VadimKleiman commented
@dzharkov

2017-03-25 14:22 UTC, dzharkov commented
Ок, 10/10

2017-03-25 14:22 UTC, closed without merging