Java01. ДЗ 03, Ёров Собир, подгруппа 1
java-course-au/assignments-2017-1 pull request #41
Opened 2017-03-15 22:56 UTC by YorovSobir

@dzharkov

2017-03-18 08:28 UTC, dzharkov requested changes
Жду исправлений и ответов на вопросы до 24/03 23:59

2017-03-18 08:28 UTC, dzharkov commented on src/main/java/ru/spbau/mit/StringSetImpl.java
> +            throws SerializationException {
Так как SerializationException unchecked исключение, его по идее можно не указывать

2017-03-18 08:28 UTC, dzharkov commented on src/main/java/ru/spbau/mit/StringSetImpl.java
> +        try {
Может просто объявит, что traverseAndDeserialize кидает IOException?
deserialize все равно ведь его ловит

2017-03-18 08:28 UTC, dzharkov commented on src/main/java/ru/spbau/mit/StringSetImpl.java
> +    private static void writeChar(DataOutputStream ostream, char value)
Необходимость этого метода непонятна по тем же причинам

2017-03-18 08:28 UTC, dzharkov commented on src/main/java/ru/spbau/mit/StringSetImpl.java
> +            writeChar(ostream, '!');
Вообще использование каких-то магических char-констант выглядит несерьезно.
Как минимум вDataOutputStream есть writeBoolean, например

2017-03-18 08:28 UTC, dzharkov commented on src/main/java/ru/spbau/mit/StringSetImpl.java
> +        writeChar(ostream, ')');
Может просто в начале ноды записать, сколько в ней детей?

2017-03-20 15:39 UTC, YorovSobir commented on src/main/java/ru/spbau/mit/StringSetImpl.java
> +            throws SerializationException {
Исправил

2017-03-20 15:44 UTC, YorovSobir commented on src/main/java/ru/spbau/mit/StringSetImpl.java
> +            writeChar(ostream, '!');
Добавил новые статические поля для этих магических констант. А с использованием boolean вместо них несогласен. Если я буду писать boolean во время сериализации то в десериализации я должен читать по одному байту, но у нас в принципе в будущем может получиться так что мы разрешим например хранить в дереве символ '\0' а у этого символа код будет таким же как и наш boolean (у нас два флага поэтому один из них точно будет false) в этом случае мы не сможем определить то что это флаг или символ строки.

2017-03-20 15:46 UTC, YorovSobir commented on src/main/java/ru/spbau/mit/StringSetImpl.java
> +        writeChar(ostream, ')');
в крайнем случае это количество может занять больше памяти чем один символ ')'. если я по этому символу могу определить количество её детей, то думаю лучше оставить так.

2017-03-20 15:48 UTC, YorovSobir commented on src/main/java/ru/spbau/mit/StringSetImpl.java
> +    private static void writeChar(DataOutputStream ostream, char value)
Я добавил этот метод, потому что не хотел в сериализации писать несколько try/catch блоков. А теперь так как добавил в объявлении метода throws IOException то этот метод реально не нужен.

2017-03-20 15:48 UTC, YorovSobir commented on src/main/java/ru/spbau/mit/StringSetImpl.java
> +        try {
Да, спасибо так лучше.

2017-03-25 14:26 UTC, dzharkov commented on src/main/java/ru/spbau/mit/StringSetImpl.java
> +        writeChar(ostream, ')');
Получится просто один `short`, ровно те же два байта по сути

2017-03-25 14:33 UTC, dzharkov commented on src/main/java/ru/spbau/mit/StringSetImpl.java
> +            writeChar(ostream, '!');
Я имел ввиду *всегда* писать boolean.
Если ты считаешь, что это расточительно, то можно, например, сохранять в `int`, как в бинарную маску информацию о всех детях, являются ли они концом слова

2017-03-25 14:35 UTC, dzharkov commented on src/main/java/ru/spbau/mit/StringSetImpl.java
> +        writeChar(ostream, ')');
Кроме того, твое решение сломается, если расширать алфавит до всех символов

2017-03-25 14:35 UTC, dzharkov requested changes
Жду исправлений и ответов на вопросы до 31/03 23:59

2017-03-30 19:04 UTC, YorovSobir commented on src/main/java/ru/spbau/mit/StringSetImpl.java
> +            writeChar(ostream, '!');
Думаю имели ввиду long (детей 52 в int не получится хранить информацию про всех). Реализовал первую идею всегда пишу boolean (легче писать эту реализацию).
Получилось намного понятнее чем было)

2017-03-30 19:04 UTC, YorovSobir commented on src/main/java/ru/spbau/mit/StringSetImpl.java
> +        writeChar(ostream, ')');
Исправил. Теперь записываю количество детей.

2017-03-30 19:07 UTC, YorovSobir commented
@dzharkov

2017-04-01 10:07 UTC, dzharkov commented
Ок, 10/10

2017-04-01 10:07 UTC, closed without merging