Java01. ДЗ 03, Кольцов Михаил, подгруппа 1
java-course-au/assignments-2017-1 pull request #44
Opened 2017-03-16 19:59 UTC by ItsLastDay

2017-03-18 08:38 UTC, dzharkov requested changes
Жду исправлений и ответов на вопросы до 24/03 23:59

2017-03-18 08:38 UTC, dzharkov commented on src/main/java/ru/spbau/mit/StringSetImpl.java
> +                isTerminal = serialReader.readBoolean();
Вообще, чтобы избежать дополнительной вложенности из-за try/catch можно вынести метод `doSerialize() throws IOException`, в котором вся логика и выполняется

2017-03-18 08:38 UTC, dzharkov commented on src/main/java/ru/spbau/mit/StringSetImpl.java
> +                        serialWriter.writeByte(0);
Может проще написать число детей в вершине в начале описания ноды?

2017-03-18 08:38 UTC, dzharkov commented on src/main/java/ru/spbau/mit/StringSetImpl.java
> +                        serialWriter.writeByte(0);
Это как минимум эффективней

2017-03-18 08:38 UTC, dzharkov commented on src/main/java/ru/spbau/mit/StringSetImpl.java
> +                subtreeCount = serialReader.readInt();
Кажется, что это совершенно лишняя информация в рамках сериализации

2017-03-19 16:25 UTC, ItsLastDay commented
Вынес методы doSerialize и doDeserialize.
Перевычисляю subtreeCount через isTerminal и значения детей.
Как писать один раз количество детей в начале - непонятно. Теперь пишу индекс ребёнка (только для тех детей, которые присутствуют) - это займёт меньше места.

2017-03-25 14:41 UTC, dzharkov commented
Ок, 10/10

2017-03-25 14:41 UTC, closed without merging