ДЗ 01, Ёров Собир, подгруппа 1
java-course-au/assignments-2017-1 pull request #5
Opened 2017-02-21 18:17 UTC by YorovSobir

2017-02-21 18:59 UTC, YorovSobir commented
@dzharkov

2017-02-25 08:56 UTC, dzharkov requested changes
Жду исправлений и ответов на вопросы до 02.03.2017 23:59

2017-02-25 08:56 UTC, dzharkov commented on src/main/java/ru/spbau/mit/StringSetImpl.java
> +    static final int ALPHABET = 26;
Я бы назвал это `ALPHABET_SIZE` тогда уж

2017-02-25 08:56 UTC, dzharkov commented on src/main/java/ru/spbau/mit/StringSetImpl.java
> +    static final int CHCNTBWLOWANDUP = 6;
Чего-то я значение это константы не понял ни из названия, ни из использования.
Кстати названия static final полей из несколько слов пишутся так: `VERY_LONG_NAME`

2017-02-25 08:56 UTC, dzharkov commented on src/main/java/ru/spbau/mit/StringSetImpl.java
> +    static final int CHARCOUNT = 2 * ALPHABET;
И все это должно быть private

2017-02-25 08:56 UTC, dzharkov commented on src/main/java/ru/spbau/mit/StringSetImpl.java
> +            next = new Vertex[CHARCOUNT];
Можно убрать конструктор, а эти присвоения перенести прямо к объявлению полей

2017-02-25 08:56 UTC, dzharkov commented on src/main/java/ru/spbau/mit/StringSetImpl.java
> +        root.isLeaf = false;
Зачем здесь это действие?

2017-02-25 08:56 UTC, dzharkov commented on src/main/java/ru/spbau/mit/StringSetImpl.java
> +        if (this.contains(element)) {
`this` чаще всего используют только для полей, когда рядом есть локальная переменная с таким же именем.
Остальные случаи использования избыточны и не рекомендуются.

2017-02-25 08:56 UTC, dzharkov commented on src/main/java/ru/spbau/mit/StringSetImpl.java
> +        temp.isLeaf = false;
Если я сначала добавлю миллион строк в бор, а затем удалю все, память не освободится,
это нужно исправить.

2017-02-25 08:56 UTC, dzharkov commented on src/main/java/ru/spbau/mit/StringSetImpl.java
> +        Vertex temp = this.root;
Здесь и в некоторых методах ниже у тебя дублируется код, который идет по дереву вниз по символам строки.
Попробуй выделить общие части **некоторых** из них в отдельный метод

2017-02-25 10:09 UTC, YorovSobir commented on src/main/java/ru/spbau/mit/StringSetImpl.java
> +    static final int ALPHABET = 26;
Исправил.

2017-02-25 10:11 UTC, YorovSobir commented on src/main/java/ru/spbau/mit/StringSetImpl.java
> +    static final int CHCNTBWLOWANDUP = 6;
Да, согласен перемудрил с этой константой. Она указывает на количество символов, которые находятся между заглавными буквами и строчными буквами в ASCII - table. Можно было обойтись без этой константы. Поэтому убрал ее и изменил функцию index(), где я и использовал эту константу.

2017-02-25 10:13 UTC, YorovSobir commented on src/main/java/ru/spbau/mit/StringSetImpl.java
> +    static final int CHARCOUNT = 2 * ALPHABET;
Они были private. Я добавил свои тесты где и использовал эти константы поэтому сделал их public. После тестирования забыл обратно сделать private. Исправил.

2017-02-25 10:13 UTC, YorovSobir commented on src/main/java/ru/spbau/mit/StringSetImpl.java
> +            next = new Vertex[CHARCOUNT];
Исправил.

2017-02-25 10:15 UTC, YorovSobir commented on src/main/java/ru/spbau/mit/StringSetImpl.java
> +        root.isLeaf = false;
Исправил. Можно убрать эту строку, так как внутри класса Vertex мы инициализируем это поле.

2017-02-25 10:15 UTC, YorovSobir commented on src/main/java/ru/spbau/mit/StringSetImpl.java
> +        if (this.contains(element)) {
Исправил.

2017-02-25 10:17 UTC, YorovSobir commented on src/main/java/ru/spbau/mit/StringSetImpl.java
> +        Vertex temp = this.root;
Исправил добавил функцию traverse(String) которая и идет по дереву по символам строки.

2017-02-25 11:20 UTC, YorovSobir commented on src/main/java/ru/spbau/mit/StringSetImpl.java
> +        temp.isLeaf = false;
Исправил

2017-03-02 21:34 UTC, YorovSobir commented
Исправил давно, но забыл оставить комментарий в конце.
@dzharkov Исправил

2017-03-07 05:50 UTC, dzharkov commented
Ок, 9/10

2017-03-07 05:50 UTC, closed without merging