Java01. ДЗ 05, Гардер Антон, подгруппа 1
java-course-au/assignments-2017-1 pull request #57
Opened 2017-03-31 13:54 UTC by avgarder

@dzharkov

2017-04-09 08:30 UTC, dzharkov requested changes
Жду исправлений и ответов на вопросы до 14/04 23:59

2017-04-09 08:30 UTC, dzharkov commented on pom.xml
> +                            <includeTestSourceDirectory>false</includeTestSourceDirectory>
А вот вам checkstyle для тестов выключать нельзя, но правило MagicConstants можно временно удалить

2017-04-09 08:30 UTC, dzharkov commented on src/main/java/ru/spbau/mit/Collections.java
> +    public static <F, T> Iterable<T> map(Function1<? super F, ? extends T> f, Iterable<F> it) {
Можешь привести пример кода, когда `? extends T` необходим?

2017-04-09 08:30 UTC, dzharkov commented on src/test/java/ru/spbau/mit/CollectionsTest.java
> +        assertTrue(equalsIterables(mapped, Arrays.asList("1", "2", "3", "4")));
Почему не просто `assertEquals`?

2017-04-09 08:30 UTC, dzharkov commented on src/test/java/ru/spbau/mit/Function2Test.java
> +        Function2<Integer, Integer, Integer> f = new Function2<Integer, Integer, Integer>() {
Какую часть библиотеки этот тест проверяет?

2017-04-09 08:30 UTC, dzharkov commented on src/test/java/ru/spbau/mit/PredicateTest.java
> +                throw new AssertionError();
В тестах общепринятый подход --- писать `fail("Msg");`

2017-04-10 18:39 UTC, avgarder commented on src/main/java/ru/spbau/mit/Collections.java
> +    public static <F, T> Iterable<T> map(Function1<? super F, ? extends T> f, Iterable<F> it) {
Function1<String, Integer> toInt = new Function1<String, Integer>() {
    @Override
    public Integer apply(String arg) {
        return Integer.parseInt(arg);
    }
};

Iterable<Number> numbers = Collections.<String, Number>map(toInt, Arrays.asList("1", "2", "3"));

2017-04-10 18:43 UTC, avgarder commented on src/test/java/ru/spbau/mit/Function2Test.java
> +        Function2<Integer, Integer, Integer> f = new Function2<Integer, Integer, Integer>() {
Самый простой тест на то, что функция корректно конструируется и вычисляется.

2017-04-10 18:44 UTC, avgarder commented on src/test/java/ru/spbau/mit/PredicateTest.java
> +                throw new AssertionError();
Тогда ещё придётся возвращать какой-то Boolean из метода.

2017-04-15 06:44 UTC, dzharkov commented on src/test/java/ru/spbau/mit/Function2Test.java
> +        Function2<Integer, Integer, Integer> f = new Function2<Integer, Integer, Integer>() {
Это по сути тест для компилятора и виртуальной машины)

2017-04-15 06:45 UTC, dzharkov commented
Ок, 10/10

2017-04-15 06:45 UTC, closed without merging