Java01. ДЗ 05, Чернявский Михаил, подгруппа 2
java-course-au/assignments-2017-1 pull request #60
Opened 2017-04-04 21:04 UTC by mchernyavsky

2017-04-04 22:24 UTC, mchernyavsky commented
@sproshev
Либо я не умею работать с JUnitParams, либо Семафор. Но тесты рабочие.

2017-04-05 12:42 UTC, sproshev commented on src/main/java/ru/spbau/mit/Collections.java
> +                .collect(Collectors.toList());
стримы использовать скорее нельзя, чем можно. поэтому если будет возможность, лучше их убрать. мы их еще типа не прошли)))

2017-04-05 17:25 UTC, mchernyavsky commented on src/main/java/ru/spbau/mit/Collections.java
> +                .collect(Collectors.toList());
Я сначала вообще использовал 9-ую джаву, чтобы и takeWhile не писать, но Семафор это не оценил.

2017-04-10 20:38 UTC, sproshev requested changes

2017-04-10 20:38 UTC, sproshev commented on src/main/java/ru/spbau/mit/Collections.java
> +    }
если у класса только 1 конструктор и тот приватный, то final можно не писать

2017-04-10 20:38 UTC, sproshev commented on src/main/java/ru/spbau/mit/Collections.java
> +    public static <T, R> Iterable<R> map(@NotNull final Function1<? super T, ? extends R> function,
см в задании возвращаемый тип

2017-04-10 20:38 UTC, sproshev commented on src/test/java/ru/spbau/mit/CollectionsTest.java
> +package ru.spbau.mit;
нет проверки wildcard'ов (не только здесь)

не проверяется ленивость предикатов

2017-04-11 06:24 UTC, mchernyavsky commented on src/main/java/ru/spbau/mit/Collections.java
> +    }
Checkstyle не согласен :(
`[ERROR] src/main/java/ru/spbau/mit/Collections.java:[10] (design) FinalClass: Class Collections should be declared as final.`

2017-04-11 06:25 UTC, mchernyavsky commented on src/test/java/ru/spbau/mit/CollectionsTest.java
> +package ru.spbau.mit;
У меня проверяется ленивость Predicate.or / Predicate.and. Например, в `testOr` я пишу `assertTrue(IS_TRUE.or(ALWAYS_THROW).apply(true))`. Или имеется ввиду что-то другое?

Я что-то туплю, но как проверять wildcard'ы?

2017-04-11 08:09 UTC, sproshev commented on src/main/java/ru/spbau/mit/Collections.java
> +    }
тогда пусть остается

2017-04-11 08:11 UTC, sproshev commented on src/test/java/ru/spbau/mit/CollectionsTest.java
> +package ru.spbau.mit;
ленивость не заметил

пример для функции map: можно коллекцию Integer'ов попробовать обработать функцией, принимающей Object

2017-04-11 14:42 UTC, mchernyavsky commented on src/test/java/ru/spbau/mit/CollectionsTest.java
> +package ru.spbau.mit;
Т.е. нужно просто проверять, что это будет компилироваться? И помечать как @Test ничего не нужно?

2017-04-11 15:32 UTC, sproshev commented on src/test/java/ru/spbau/mit/CollectionsTest.java
> +package ru.spbau.mit;
пусть прогонится как `@Test`, хуже от этого не будет

можно эти тесты получить копипастой уже существующих, с небольшими модификациями

2017-04-11 16:18 UTC, mchernyavsky commented on src/test/java/ru/spbau/mit/CollectionsTest.java
> +package ru.spbau.mit;
Вроде бы готово, но выглядит странно.

Я теперь не уверен, что некоторые wildcard'ы (у возвращаемых значений) нужны, т.к. оказалось, что и без них все прекрасно компилируется. Но вот [здесь](https://docs.oracle.com/javase/tutorial/extra/generics/morefun.html) написано, что:
> In general, if you have an API that only uses a type parameter T as an argument, its uses should take advantage of lower bounded wildcards (`? super T`). Conversely, if the API only returns T, you'll give your clients more flexibility by using upper bounded wildcards (`? extends T`).

Есть какой-нибудь пример полезности `? extends T` у возвращаемых значений в нашем задании?

2017-04-12 15:39 UTC, sproshev commented on src/test/java/ru/spbau/mit/CollectionsTest.java
> +package ru.spbau.mit;
я так понимаю, читать текст надо так:

```
.... by using upper bounded wildcards (? extends T) in parameters.
```

это вроде соответствует примерам кода по той ссылке.

`? extends T` в возвращаемых значениях может привести к неизменяемости возвращенных значений (рассказывал на паре на примере списка), но функциям в нашем задании это безразлично

2017-04-22 20:52 UTC, sproshev commented
10

2017-04-23 18:35 UTC, closed without merging