Java 01. ДЗ 05, Ёров Собир, подгруппа 1
java-course-au/assignments-2017-1 pull request #61
Opened 2017-04-05 18:52 UTC by YorovSobir

@dzharkov

2017-04-09 08:47 UTC, dzharkov requested changes
Жду исправлений и ответов на вопросы до 14/04 23:59

2017-04-09 08:47 UTC, dzharkov commented on src/main/java/ru/spbau/mit/Function1.java
> +public abstract class Function1<R, X> {
Обычно в `FunctionN` сначала идут типовые параметры для аргументов функции, а параметр результата в конце

2017-04-09 08:47 UTC, dzharkov commented on src/main/java/ru/spbau/mit/Collections.java
> +        List<Function1<R, ? super R>> funcList = new ArrayList<>();
Зачем нужен этот список?

2017-04-09 08:47 UTC, dzharkov commented on src/test/java/ru/spbau/mit/FunctionsForTesting.java
> +    static <T> boolean compareCollections(Iterable<T> col1, Iterable<T> col2) {
Обычно у коллекций `equals` работает не хуже

2017-04-09 08:47 UTC, dzharkov commented on src/test/java/ru/spbau/mit/FunctionsForTesting.java
> +public final class FunctionsForTesting {
Обычно такие классы назвают `TestUtils`

2017-04-09 08:47 UTC, dzharkov commented on src/test/java/ru/spbau/mit/TestAll.java
> +    public void testFunction1() {
Обычно юнит-тесты проверяют какую-то обособленную функциональность класса, например один метод.
У тебя тут все сразу, это очень неудобно. потому что если какая-то часть сломается, будет сложнее идентифицировать, какая именно

2017-04-09 08:47 UTC, dzharkov commented on src/test/java/ru/spbau/mit/TestAll.java
> +        for (int i = 0; i < SIZE; ++i) {
Намного удобнее отлаживать тесты, когда у тебя недлинные константные списки

2017-04-09 08:47 UTC, dzharkov commented on src/test/java/ru/spbau/mit/TestAll.java
> +        res = Collections.foldr(sum(), 1, integerList);
А можно придумать тест, который будет для fold и foldr выдавать разные результаты?

2017-04-09 08:47 UTC, dzharkov commented on src/test/java/ru/spbau/mit/TestAll.java
> +            res = Collections.filter(lessThan(i).or(greaterThan(i)), integerList);
Не проверяется ленивость or/and

2017-04-14 08:36 UTC, YorovSobir commented on src/main/java/ru/spbau/mit/Function1.java
> +public abstract class Function1<R, X> {
Я писал по аналогии с std::function из c++ а там сначала возвращаемое значение потом аргументы.

2017-04-14 08:37 UTC, YorovSobir commented on src/main/java/ru/spbau/mit/Function1.java
> +public abstract class Function1<R, X> {
Исправил, теперь сначала аргументы потом возвращаемое значение.

2017-04-14 15:25 UTC, YorovSobir commented on src/main/java/ru/spbau/mit/Collections.java
> +        List<Function1<R, ? super R>> funcList = new ArrayList<>();
Написал по аналогии с foldr чтобы хранить результаты применения функций к элементам коллекции. Можно обойтись и без списка, т.к foldl леворекурсивный и мы можем за один проход посчитать результат свертки. Исправил.

2017-04-14 15:25 UTC, YorovSobir commented on src/test/java/ru/spbau/mit/FunctionsForTesting.java
> +public final class FunctionsForTesting {
Исправил

2017-04-14 18:19 UTC, YorovSobir commented on src/test/java/ru/spbau/mit/FunctionsForTesting.java
> +    static <T> boolean compareCollections(Iterable<T> col1, Iterable<T> col2) {
Исправил

2017-04-14 18:20 UTC, YorovSobir commented on src/test/java/ru/spbau/mit/TestAll.java
> +    public void testFunction1() {
Исправил

2017-04-14 18:20 UTC, YorovSobir commented on src/test/java/ru/spbau/mit/TestAll.java
> +        for (int i = 0; i < SIZE; ++i) {
Исправил

2017-04-14 18:24 UTC, YorovSobir commented on src/test/java/ru/spbau/mit/TestAll.java
> +        res = Collections.foldr(sum(), 1, integerList);
да можно, добавил в тесты. Можно передать функцию const (haskell) и будет разное значение если initial не совпадает с первым элементом контейнера.

2017-04-14 18:28 UTC, YorovSobir commented on src/test/java/ru/spbau/mit/TestAll.java
> +            res = Collections.filter(lessThan(i).or(greaterThan(i)), integerList);
Исправил. Добавил тесты.

2017-04-14 18:31 UTC, YorovSobir commented
@dzharkov

2017-04-15 06:47 UTC, dzharkov commented
Ок, 10/10

2017-04-15 06:47 UTC, closed without merging