Java 01. ДЗ 05, Кручинин Дмитрий, подгруппа 1
java-course-au/assignments-2017-1 pull request #62
Opened 2017-04-06 17:10 UTC by KruchDmitriy

2017-04-09 09:07 UTC, dzharkov requested changes
Жду исправлений и ответов на вопросы до 14/04 23:59

2017-04-09 09:07 UTC, dzharkov commented on src/main/java/ru/spbau/mit/Collections.java
> +    public static <X, Y, Container extends Iterable<X>>
Можешь привести пример, когда параметр `Container` необходим?

2017-04-09 09:07 UTC, dzharkov commented on src/main/java/ru/spbau/mit/Predicate.java
> +                    return Boolean.TRUE;
почему не просто `return true`?

2017-04-09 09:07 UTC, dzharkov commented on src/test/java/ru/spbau/mit/CollectionsTest.java
> +    private Function1<Integer, Integer> sqr =
Это явный кандидат для `static` - по сути константа, -1

2017-04-09 09:07 UTC, dzharkov commented on src/test/java/ru/spbau/mit/CollectionsTest.java
> +        sequence = new ArrayList<>(ARRAY_LENGTH);
Намного удобнее отлаживать тесты, когда у тебя недлинные константные списки

2017-04-09 09:07 UTC, dzharkov commented on src/test/java/ru/spbau/mit/CollectionsTest.java
> +    private final Random random = new Random();
Настоящая рандомность в тестах — зло, можешь сказать, почему?

2017-04-09 09:07 UTC, dzharkov commented on src/test/java/ru/spbau/mit/CollectionsTest.java
> +        Function2<Number, Number, Number> sum =
Много копипаста в тестах

2017-04-09 09:07 UTC, dzharkov commented on src/test/java/ru/spbau/mit/CollectionsTest.java
> +        Number value = Collections.foldl(sequence, sum, 0);
А можно придумать тест, который будет для fold и foldr выдавать разные результаты?

2017-04-09 09:07 UTC, dzharkov commented on src/test/java/ru/spbau/mit/FunctionalTest.java
> +        assertTrue(Predicate.ALWAYS_TRUE.and(Predicate.ALWAYS_TRUE).apply(
Не проверяется ленивость or/and

2017-04-09 09:07 UTC, dzharkov commented on src/test/java/ru/spbau/mit/CollectionsTest.java
> +    public void foldrTest() {
Обычно методы называют `testSomeMethod`

2017-04-14 19:31 UTC, KruchDmitriy commented on src/test/java/ru/spbau/mit/CollectionsTest.java
> +    private final Random random = new Random();
Если тест вдруг не прошел сложно восстановить сценарий с которым все свалилось. Здесь, я подумал, что это не так страшно поскольку нет большой сложной структуры, если что-то упало, то значит просто этот метод неправильно работает.

2017-04-14 19:42 UTC, KruchDmitriy commented on src/test/java/ru/spbau/mit/CollectionsTest.java
> +        sequence = new ArrayList<>(ARRAY_LENGTH);
Я, к сожалению, не до конца понял, что Вы здесь имели в виду. Уменьшил длину массива.

2017-04-15 06:49 UTC, dzharkov commented on src/test/java/ru/spbau/mit/CollectionsTest.java
> +        sequence = new ArrayList<>(ARRAY_LENGTH);
Я имел ввиду, что списки заполняются не в цикле а заданы в коде: `Arrays.aslList(1, 1, 2, 3, 5, 7)`

2017-04-15 06:52 UTC, dzharkov commented
Ок, 9/10

2017-04-15 06:52 UTC, closed without merging