Java 01. ДЗ 05, Клейман Вадим, подгруппа 1
java-course-au/assignments-2017-1 pull request #63
Opened 2017-04-06 18:15 UTC by VadimKleiman

@dzharkov

2017-04-09 09:15 UTC, dzharkov requested changes
Жду исправлений и ответов на вопросы до 14/04 23:59

2017-04-09 09:15 UTC, dzharkov commented on src/main/java/ru/spbau/mit/Collections.java
> +    static <X, Y> X foldl(Functional2<? super X, ? super Y, X> f, X start, Iterable<Y> c) {
В `fold`'ах лучше избавиться от рекурсии, хотя бы в одном из них

2017-04-09 09:15 UTC, dzharkov commented on src/main/java/ru/spbau/mit/Predicate.java
> +                return g.apply(x) || Predicate.this.apply(x);
Неожиданно: `p1.or(p2)` будет работать как `p2(x) || p1(x)`

2017-04-09 09:15 UTC, dzharkov commented on src/test/java/ru/spbau/mit/CollectionsTest.java
> +            list.add(i);
Намного удобнее отлаживать тесты, когда у тебя недлинные константные списки

2017-04-09 09:15 UTC, dzharkov commented on src/test/java/ru/spbau/mit/CollectionsTest.java
> +        for (int i = 0; i < n; i++) {
Можно же просто `asserEquals` для коллекций вызвать?

2017-04-09 09:15 UTC, dzharkov commented on src/test/java/ru/spbau/mit/CollectionsTest.java
> +    public void map() throws Exception {
Обычно методы называют `testSomeMethod`

2017-04-09 09:15 UTC, dzharkov commented on src/test/java/ru/spbau/mit/CollectionsTest.java
> +        Predicate<Integer> f = new Predicate<Integer>() {
Очень много копипасты в тестах

2017-04-09 09:15 UTC, dzharkov commented on src/test/java/ru/spbau/mit/CollectionsTest.java
> +        Functional2<Integer, Integer, Integer> u = new Functional2<Integer, Integer, Integer>() {
Совсем много, -1

2017-04-09 09:15 UTC, dzharkov commented on src/test/java/ru/spbau/mit/CollectionsTest.java
> +        Functional2<Integer, Integer, Integer> u = new Functional2<Integer, Integer, Integer>() {
А можно придумать тест, который будет для fold и foldr выдавать разные результаты?

2017-04-09 09:15 UTC, dzharkov commented on src/test/java/ru/spbau/mit/PredicateTest.java
> +        and = v.and(u);
Не проверяется ленивость or/and

2017-04-14 20:10 UTC, VadimKleiman commented on src/main/java/ru/spbau/mit/Collections.java
> +    static <X, Y> X foldl(Functional2<? super X, ? super Y, X> f, X start, Iterable<Y> c) {
Реализовал нерекурсивный foldl

2017-04-14 20:10 UTC, VadimKleiman commented on src/main/java/ru/spbau/mit/Predicate.java
> +                return g.apply(x) || Predicate.this.apply(x);
Исправил

2017-04-14 20:10 UTC, VadimKleiman commented on src/test/java/ru/spbau/mit/CollectionsTest.java
> +    public void map() throws Exception {
Исправил

2017-04-14 20:10 UTC, VadimKleiman commented on src/test/java/ru/spbau/mit/CollectionsTest.java
> +            list.add(i);
Исправил

2017-04-14 20:11 UTC, VadimKleiman commented on src/test/java/ru/spbau/mit/CollectionsTest.java
> +        for (int i = 0; i < n; i++) {
Да, можно. Сразу не подумал.

2017-04-14 20:11 UTC, VadimKleiman commented on src/test/java/ru/spbau/mit/CollectionsTest.java
> +        Predicate<Integer> f = new Predicate<Integer>() {
Исправил

2017-04-14 20:11 UTC, VadimKleiman commented on src/test/java/ru/spbau/mit/CollectionsTest.java
> +        Functional2<Integer, Integer, Integer> u = new Functional2<Integer, Integer, Integer>() {
Исправил

2017-04-14 20:12 UTC, VadimKleiman commented on src/test/java/ru/spbau/mit/CollectionsTest.java
> +        Functional2<Integer, Integer, Integer> u = new Functional2<Integer, Integer, Integer>() {
Поправил тесты

2017-04-14 20:12 UTC, VadimKleiman commented on src/test/java/ru/spbau/mit/PredicateTest.java
> +        and = v.and(u);
Добавил проверку на ленивость

2017-04-15 06:58 UTC, dzharkov requested changes
Жду исправлений и ответов на вопросы до 21/04 23:59

2017-04-15 06:58 UTC, dzharkov commented on src/test/java/ru/spbau/mit/CollectionsTest.java
> +    private static final Functional2<Integer, Integer, Integer> FUNC =
Название `FUNC` плохое, из без перехода к декларации невозможно понять, что она делает :(

2017-04-15 06:58 UTC, dzharkov commented on src/test/java/ru/spbau/mit/CollectionsTest.java
> +        final Integer check = -45;
Правило MagicConstant в checkstyle можно отключить

2017-04-15 06:58 UTC, dzharkov commented on src/test/java/ru/spbau/mit/CollectionsTest.java
> +        final Integer check = -45;
После этого все такие константы можно заинлайнить

2017-04-15 06:58 UTC, dzharkov commented on src/test/java/ru/spbau/mit/CollectionsTest.java
> +    private static final Integer[] SAMPLE = new Integer[] {0, 1, 2, 3, 4, 5, 6, 7, 8, 9};
Это поле я бы тоже как-то иначе назвал

2017-04-21 19:07 UTC, VadimKleiman commented on src/test/java/ru/spbau/mit/CollectionsTest.java
> +    private static final Integer[] SAMPLE = new Integer[] {0, 1, 2, 3, 4, 5, 6, 7, 8, 9};
Переименовал

2017-04-21 19:07 UTC, VadimKleiman commented on src/test/java/ru/spbau/mit/CollectionsTest.java
> +    private static final Functional2<Integer, Integer, Integer> FUNC =
Исправил

2017-04-21 19:07 UTC, VadimKleiman commented on src/test/java/ru/spbau/mit/CollectionsTest.java
> +        final Integer check = -45;
Исправил

2017-04-22 09:07 UTC, dzharkov commented
Ок, 9/10

2017-04-22 09:07 UTC, closed without merging