Java 01. ДЗ 05, Симиютин Борис, подгруппа 1
java-course-au/assignments-2017-1 pull request #65
Opened 2017-04-06 20:40 UTC by simiyutin

2017-04-09 09:48 UTC, dzharkov commented
К сожалению семафор по каким-то причинам отвалился, но у тебя checkstyle не проходится
Пиши, как получишь успешный `mvn clean install`

2017-04-09 10:13 UTC, simiyutin commented
@dzharkov, поправил

2017-04-15 07:27 UTC, dzharkov requested changes
Жду исправлений и ответов на вопросы до 21/04 23:59

2017-04-15 07:27 UTC, dzharkov commented on src/main/java/ru/spbau/mit/Collections.java
> +    public static <X, T> T foldr(Function2<? super X, ? super T, ? extends T> f, T ini, Iterable<X> xs) {
Можно хотя бы одну из сверток сделать нерекурсивной?

2017-04-15 07:27 UTC, dzharkov commented on src/main/java/ru/spbau/mit/Collections.java
> +    public static <T, R> Iterable<R> map(Function1<? super T, ? extends R> mapper, Iterable<T> xs) {
Можешь привести пример кода, когда `? extends R` в этой сигнатуре необходим, и без него не скомпилируется?

2017-04-15 07:27 UTC, dzharkov commented on src/main/java/ru/spbau/mit/Predicate.java
> +    public static final Predicate<?> ALWAYS_TRUE = new Predicate<Object>() {
Не очень удобный предикат получился. Можешь сказать почему?

2017-04-15 07:27 UTC, dzharkov commented on src/test/java/ru/spbau/mit/FunctionalTests.java
> +        final int a = 20;
правило MagicConstants можно временно удалить и заинлайнить такие константы

2017-04-15 07:27 UTC, dzharkov commented on src/test/java/ru/spbau/mit/FunctionalTests.java
> +    public void foldrTest() {
Обычно методы называют `testSomeMethod`

2017-04-15 07:27 UTC, dzharkov commented on src/test/java/ru/spbau/mit/FunctionalTests.java
> +        list.add(1);
`Arrays.asList`?

2017-04-15 07:27 UTC, dzharkov commented on src/test/java/ru/spbau/mit/FunctionalTests.java
> +        Function2<Integer, Integer, Integer> add = new Function2<Integer, Integer, Integer>() {
Вообще этот тест очевидным образом делится на два

2017-04-15 07:27 UTC, dzharkov commented on src/test/java/ru/spbau/mit/FunctionalTests.java
> +        assertTrue(list.equals(same));
`assertEquals`

2017-04-15 07:27 UTC, dzharkov commented on src/test/java/ru/spbau/mit/FunctionalTests.java
> +        assertTrue(isEven.or(isOdd).test(a));
Обычно юнит-тесты проверяют какую-то обособленную функциональность класса, например один метод.
У тебя тут все сразу, это очень неудобно. потому что если какая-то часть сломается, будет сложнее идентифицировать, какая именно

2017-04-15 07:27 UTC, dzharkov commented on src/test/java/ru/spbau/mit/FunctionalTests.java
> +        assertTrue(isEven.or(isOdd).test(a));
Не проверяется ленивость or/and

2017-04-21 17:22 UTC, simiyutin commented on src/main/java/ru/spbau/mit/Collections.java
> +    public static <T, R> Iterable<R> map(Function1<? super T, ? extends R> mapper, Iterable<T> xs) {
List<Integer> list = Arrays.asList(1, 2, 3, 4, 5);

        Iterable<Object> mapped2 = Collections.map(new Function1<Object, String>() {
            @Override
            public String apply(Object obj) {
                return obj.toString();
            }
        }, list);

2017-04-21 17:24 UTC, simiyutin commented on src/main/java/ru/spbau/mit/Predicate.java
> +    public static final Predicate<?> ALWAYS_TRUE = new Predicate<Object>() {
Потому что компилятор не знает тип параметров, которые надо передать в функцию test, и не можем ее ни с чем вызвать, кроме null, который подходит везде.

2017-04-21 17:30 UTC, simiyutin commented
@dzharkov, все пофикшено

2017-04-22 09:06 UTC, dzharkov commented
Ок, 10/10

2017-04-22 09:06 UTC, closed without merging