Java01. ДЗ 01, Кручинин Дмитрий, подгруппа 1
java-course-au/assignments-2017-1 pull request #7
Opened 2017-02-21 19:28 UTC by KruchDmitriy

@dzharkov

2017-02-25 09:16 UTC, dzharkov requested changes
Жду исправлений и ответов на вопросы до 02.03.2017 23:59

2017-02-25 09:16 UTC, dzharkov commented on src/main/java/ru/spbau/mit/StringSetImpl.java
> +        nodes = new Node[NUMBER_OF_LETTERS];
Можно убрать конструктор, а эти присвоения перенести прямо к объявлению полей

2017-02-25 09:16 UTC, dzharkov commented on src/main/java/ru/spbau/mit/StringSetImpl.java
> +class Node {
Этот класс лучше сделать private static и перенести в StringSetImpl, на паре расскажу почему.

2017-02-25 09:16 UTC, dzharkov commented on src/main/java/ru/spbau/mit/StringSetImpl.java
> +    private int idxFromChar(char chr) {
1. Может быть статическим
2. В общем случае не рекомендуется использовать сокращения вроде idx/res
3. Если быть совсем занудой, то методы в джаве должны начинаться с глагола

2017-02-25 09:16 UTC, dzharkov commented on src/main/java/ru/spbau/mit/StringSetImpl.java
> +            Node curNode = root;
Я бы сказал, что else-блок здесь лишний, так как if заканчивается возвратом.
При этом читаемость кода из-за вложенности страдает

2017-02-25 09:16 UTC, dzharkov commented on src/main/java/ru/spbau/mit/StringSetImpl.java
> +                if (curNode.getNext(element.charAt(i)) == null) {
Я бы создал переменную для `element.charAt(i)`, это выражение три раза повторяется

2017-02-25 09:16 UTC, dzharkov commented on src/main/java/ru/spbau/mit/StringSetImpl.java
> +        Node curNode = root;
Здесь и в некоторых методах ниже у тебя дублируется код, который идет по дереву вниз по символам строки.
Попробуй выделить общие части **некоторых** из них в отдельный метод

2017-02-25 09:17 UTC, dzharkov requested changes

2017-02-25 09:17 UTC, dzharkov commented on src/main/java/ru/spbau/mit/StringSetImpl.java
> +            curNode.decreaseNumStrings();
Если я сначала добавлю миллион строк в бор, а затем удалю все, память не освободится,
это нужно исправить.

2017-02-25 13:36 UTC, KruchDmitriy commented
@dzharkov, исправил.

2017-03-07 05:57 UTC, dzharkov commented
Ок, 9/10

2017-03-07 05:57 UTC, closed without merging