Java01. ДЗ 04, Кольцов Михаил, подгруппа 1
java-course-au/assignments-2017-1 pull request #75
Opened 2017-04-07 20:38 UTC by ItsLastDay

2017-04-09 09:56 UTC, dzharkov requested changes
Жду исправлений и ответов на вопросы до 14/04 23:59

2017-04-09 09:56 UTC, dzharkov commented on pom.xml
> +                            <includeTestSourceDirectory>false</includeTestSourceDirectory>
А вот вам checkstyle для тестов выключать нельзя, но правило MagicConstants можно временно удалить

2017-04-09 09:56 UTC, dzharkov commented on src/main/java/ru/spbau/mit/Collections.java
> +    public static <A, R> Collection<R> map(Function1<? super A, ? extends R> func,
Можешь привести пример, когда нужны `? extends`?

2017-04-09 09:56 UTC, dzharkov commented on src/main/java/ru/spbau/mit/Predicate.java
> +    public static final Predicate ALWAYS_TRUE = new Predicate() {
Почему не `Predicate<Object>`?

2017-04-09 09:56 UTC, dzharkov commented on src/test/java/ru/spbau/mit/FunctionsAndCollectionsTest.java
> +        assertEquals(resL, resR);
А можно придумать тест, который будет для fold и foldr выдавать разные результаты?

2017-04-09 09:56 UTC, dzharkov commented on src/test/java/ru/spbau/mit/FunctionsAndCollectionsTest.java
> +        assertEquals(resL, resR);
Кстати, нам правда нужно проверять факториал больших чисел?

2017-04-09 09:56 UTC, dzharkov commented on src/test/java/ru/spbau/mit/FunctionsAndCollectionsTest.java
> +    public void funWithStrings() {
Обычно методы называют `testSomeMethod`

2017-04-09 09:56 UTC, dzharkov commented on src/test/java/ru/spbau/mit/FunctionsAndCollectionsTest.java
> +        for (int i = 1; i <= 10; i++) {
Я предпочитаю в тестах использовать константы, так сразу видно, что происходит

2017-04-09 09:56 UTC, dzharkov commented on src/test/java/ru/spbau/mit/FunctionsAndCollectionsTest.java
> +        Function1<String, Integer> funToUppercaseLength = funUppercase.compose(funLength);
Обычно юнит-тесты проверяют какую-то обособленную функциональность класса, например один метод.
У тебя тут все сразу, это очень неудобно. потому что если какая-то часть сломается, будет сложнее идентифицировать, какая именно

2017-04-09 09:56 UTC, dzharkov commented on src/test/java/ru/spbau/mit/FunctionsAndCollectionsTest.java
> +        for (int i = 1; i <= 10; i++) {
Вот реально я минуты две понимал, что у тебя здесь происходит

2017-04-13 23:23 UTC, ItsLastDay commented on src/main/java/ru/spbau/mit/Collections.java
> +    public static <A, R> Collection<R> map(Function1<? super A, ? extends R> func,
Добавил тест testMapFuncWildcard: если убрать extends в возвращаемом значении функции или в принимаемой коллекции, то он не компилируется.

2017-04-13 23:26 UTC, ItsLastDay commented on src/main/java/ru/spbau/mit/Predicate.java
> +    public static final Predicate ALWAYS_TRUE = new Predicate() {
У меня были проблемы с вызовом в стиле
ALWAYS_TRUE.or(some_predicate)
так как потом ожидалось, что some_predicate будет работать на object-ах.
Но теперь я подумал, что так никто не должен делать (т.е. цеплять после ALWAYS_TRUE что-то не имеет смысла), поэтому сделал Predicate<Object>.

2017-04-13 23:27 UTC, ItsLastDay commented on src/test/java/ru/spbau/mit/FunctionsAndCollectionsTest.java
> +        assertEquals(resL, resR);
Добавил тест на разные результаты: testMapFuncWildcard
Факториал теперь вычисляю от маленьких чисел.

2017-04-13 23:29 UTC, ItsLastDay commented
Зарефакторил тесты: теперь методы со слова test начинаются; тесты разбиты на классы; есть TestUtils со всякими штуками, которые не хочется копировать (они все имеют геттер, потому что иначе checkStyle ругается).

2017-04-15 07:28 UTC, dzharkov commented
Ок, 10/10

2017-04-15 07:28 UTC, closed without merging