Java 01. ДЗ 05, Лапицкая Людмила, подгруппа 1
java-course-au/assignments-2017-1 pull request #76
Opened 2017-04-07 20:57 UTC by bugogish

2017-04-09 10:21 UTC, dzharkov requested changes
Жду исправлений и ответов на вопросы до 14/04 23:59

2017-04-09 10:21 UTC, dzharkov commented on src/main/java/ru/spbau/mit/Collections.java
> +    public static <A1, R> Iterable<R> map(Function1<? super A1, ? extends R> func, Iterable<A1> collection) {
Можешь привести пример кода, когда `? extends R` в этой сигнатуре необходим, и без него не скомпилируется?

2017-04-09 10:21 UTC, dzharkov commented on pom.xml
> +                            <includeTestSourceDirectory>false</includeTestSourceDirectory>
А вот вам checkstyle для тестов выключать нельзя, но правило MagicConstants можно временно удалить

2017-04-09 10:21 UTC, dzharkov commented on src/main/java/ru/spbau/mit/Predicate.java
> +                if (Predicate.this.apply(argument)) {
Оператором `||` никто пользоваться не запрещал :)

2017-04-09 10:21 UTC, dzharkov commented on src/main/java/ru/spbau/mit/Predicate.java
> +            return Boolean.TRUE;
Почему не `return true`?

2017-04-09 10:21 UTC, dzharkov commented on src/test/java/ru/spbau/mit/TestCollections.java
> +        for (int i = 0; i < COL_SIZE; i++) {
Намного удобнее отлаживать тесты, когда у тебя недлинные константные списки

2017-04-09 10:21 UTC, dzharkov commented on src/test/java/ru/spbau/mit/TestCollections.java
> +        final int addend = 10;
Лучше бы ее заинлайнить

2017-04-09 10:21 UTC, dzharkov commented on src/test/java/ru/spbau/mit/TestCollections.java
> +        for (int i = 0; i < COL_SIZE; i++) {
Можно же просто `assertEquals` для коллекций вызвать?

2017-04-09 10:21 UTC, dzharkov commented on src/test/java/ru/spbau/mit/TestCollections.java
> +    public void testFoldL() {
foldr не покрыт тестами, -1

2017-04-09 10:21 UTC, dzharkov commented on src/test/java/ru/spbau/mit/TestPredicate.java
> +    public void testOrPredicate() {
Не проверяется ленивость or/and

2017-04-09 10:21 UTC, dzharkov commented on src/test/java/ru/spbau/mit/TestPredicate.java
> +        final int value1 = 10;
Эти константы тоже можно заинлайнить, отключив соответствующую проверку в checkstyle

2017-04-14 19:18 UTC, bugogish commented on src/main/java/ru/spbau/mit/Collections.java
> +    public static <A1, R> Iterable<R> map(Function1<? super A1, ? extends R> func, Iterable<A1> collection) {
Если убрать ? extends R, то в map можно будет подать только функции строго с возвращаемым значением R и никакие другие, хотя если у R есть наследники было бы логично принимать функции, которые умеют возвращать наследников R тоже, так как их можно скастить к R. В частности, если я хочу на выходе из map получить `Iterable <Object>`, то в качестве примера подойдет какой угодно возвращаемый параметр у Function1, кроме Object, и код не скомпилируется:
````
String[] array = {"8", "9", "10", "11", "12"};
 
Function1<String, Integer> len = new Function1<String, Integer>() {  
            @Override  
            public Integer apply(String argument) {   
                return argument.length();  
            }  
        };  
Iterable<Object> mapped1 =  Collections.<String, Object>map(len, Arrays.asList(array));  
````

2017-04-15 07:32 UTC, dzharkov commented
Ок, 9/10

2017-04-15 07:32 UTC, closed without merging