Java01. ДЗ 06, Симиютин Борис, подгруппа 1
java-course-au/assignments-2017-1 pull request #79
Opened 2017-04-26 21:52 UTC by simiyutin

2017-05-01 06:25 UTC, dzharkov requested changes
Жду исправлений и ответов на вопросы до 08.05 23:59

2017-05-01 06:25 UTC, dzharkov commented on src/main/java/ru/spbau/mit/FirstPartTasks.java
> +                .collect(Collectors.groupingBy(e -> e))
Function.identity()

2017-05-01 06:25 UTC, dzharkov commented on src/main/java/ru/spbau/mit/FirstPartTasks.java
> +        return albums.min(Comparator.comparing(album -> album
Чаще всего первый аргумент в таких случай переносят на следующую строку левее открывающей скобки

2017-05-01 06:25 UTC, dzharkov commented on src/main/java/ru/spbau/mit/FirstPartTasks.java
> +        return s.filter(clazz::isInstance).map(clazz::cast);
O(n) лишних операций

2017-05-01 06:25 UTC, dzharkov commented on src/main/java/ru/spbau/mit/SecondPartTasks.java
> +        double xVal = new Random().nextDouble() - radius;
Обычно объект `Random` фиксируют для всего эксперимента, в случае чего так проще фиксировать какой-то seed для отладки

2017-05-05 20:43 UTC, simiyutin commented
все пофикшено

2017-05-13 08:15 UTC, dzharkov commented
Ок, 10/10

2017-05-13 08:15 UTC, closed without merging