Java01. ДЗ 06, Кручинин Дмитрий, подгруппа 1
java-course-au/assignments-2017-1 pull request #84
Opened 2017-04-27 18:21 UTC by KruchDmitriy

2017-05-01 06:33 UTC, dzharkov requested changes
Жду исправлений и ответов на вопросы до 08.05 23:59

2017-05-01 06:33 UTC, dzharkov commented on src/main/java/ru/spbau/mit/FirstPartTasks.java
> +                .flatMap((album) -> album.getTracks().stream())
Лишние скобки для параметра лямбды, -1

2017-05-01 06:33 UTC, dzharkov commented on src/main/java/ru/spbau/mit/FirstPartTasks.java
> +                .map(clazz::cast);
O(n) лишних операций

2017-05-01 06:33 UTC, dzharkov commented on src/main/java/ru/spbau/mit/FirstPartTasks.java
> +        return "<".concat(
Каждый вызов `concat` -- лишнее копирование всей строки

2017-05-01 06:38 UTC, KruchDmitriy commented on src/main/java/ru/spbau/mit/FirstPartTasks.java
> +                .flatMap((album) -> album.getTracks().stream())
Почему -1? Раньше же Вы такого замечания мне не делали, это первый раз.

2017-05-02 08:23 UTC, dzharkov commented on src/main/java/ru/spbau/mit/FirstPartTasks.java
> +                .flatMap((album) -> album.getTracks().stream())
Конкретно про это я предупреждал на паре

2017-05-13 08:17 UTC, dzharkov commented
Ок, 9/10

2017-05-13 08:17 UTC, closed without merging