Java01. ДЗ 05, Кольцов Михаил, подгруппа 1
java-course-au/assignments-2017-1 pull request #86
Opened 2017-04-27 20:50 UTC by ItsLastDay

2017-05-01 06:48 UTC, dzharkov requested changes
Жду исправлений и ответов на вопросы до 08.05 23:59

2017-05-01 06:48 UTC, dzharkov commented on src/main/java/ru/spbau/mit/FirstPartTasks.java
> +        return s.filter(clazz::isInstance).map(clazz::cast);
O(n) лишних операций

2017-05-01 06:48 UTC, dzharkov commented on src/main/java/ru/spbau/mit/SecondPartTasks.java
> +        BinaryOperator<Map<String, Integer>> merger = (m1, m2) -> {
Попробуй сделать сначала стрим из всех вообще Map.Entry, а затем заного их сгруппировать с `summingInt`

2017-05-01 20:30 UTC, ItsLastDay commented
@dzharkov 
В задании про clazz и cast-ы убрал map - заменил его на unchecked cast всего стрима.
В задании про слияние map-ов сделал, как вы сказали.

2017-05-13 08:20 UTC, dzharkov commented
Ок, 10/10

2017-05-13 08:20 UTC, closed without merging