Java01. ДЗ 05, Ёров Собир, подгруппа 1
java-course-au/assignments-2017-1 pull request #87
Opened 2017-04-27 21:12 UTC by YorovSobir

@dzharkov

2017-05-01 07:04 UTC, dzharkov requested changes
Жду исправлений и ответов на вопросы до 08.05 23:59

2017-05-01 07:04 UTC, dzharkov commented on src/main/java/ru/spbau/mit/FirstPartTasks.java
> +                .map(obj -> (R) obj);
O(n) лишних операций

2017-05-05 16:53 UTC, YorovSobir commented on src/main/java/ru/spbau/mit/FirstPartTasks.java
> +                .map(obj -> (R) obj);
Исправил

2017-05-13 08:19 UTC, dzharkov commented
Ок, 10/10

2017-05-13 08:19 UTC, closed without merging