Java01. MemoryLeakLimit, Гардер Антон, подгруппа 1
java-course-au/assignments-2017-1 pull request #88
Opened 2017-04-28 08:49 UTC by avgarder

@dzharkov

2017-05-13 08:32 UTC, dzharkov commented
Жду исправлений до 19.05.2017 23:59

2017-05-13 08:32 UTC, dzharkov requested changes

2017-05-13 08:32 UTC, dzharkov commented on src/test/java/ru/spbau/mit/MemoryLeakLimit.java
> +                statement.evaluate();
А если случится исключение?
Не забудь тест написать

2017-05-13 08:32 UTC, dzharkov commented on src/test/java/ru/spbau/mit/MemoryLeakLimit.java
> +                statement.evaluate();
Буду считать это важным косяком, -1

2017-05-13 11:24 UTC, avgarder commented on src/test/java/ru/spbau/mit/MemoryLeakLimit.java
> +                statement.evaluate();
@dzharkov 
Не очень понимаю в чём здесь проблема. Исключения из самого теста из evaluate не пробрасываются, значит исключение может быть только "из внутренностей" junit и из других правил. Такие исключения обрабатывать непонятно как, поэтому я просто проброшу их дальше.

Для какого случая предлагается написать тест?

2017-05-13 16:35 UTC, dzharkov commented on src/test/java/ru/spbau/mit/MemoryLeakLimit.java
> +                statement.evaluate();
@avgarder Тест может считаться пройденным даже с проброшенным экспепшеном, но и в этом случае утечки памяти не должно происходить

2017-05-13 16:35 UTC, dzharkov commented on src/test/java/ru/spbau/mit/MemoryLeakLimit.java
> +                statement.evaluate();
Тест именно на такой случай

2017-05-15 06:34 UTC, avgarder commented
@dzharkov

2017-05-21 07:32 UTC, dzharkov commented
Вообще, я намекал, что нужно добавить try-catch в коде рула, ну да ладно.
Ок, 9/10

2017-05-21 07:32 UTC, closed without merging