Java01. MemoryLeakLimit, Кольцов Михаил, подгруппа 1
java-course-au/assignments-2017-1 pull request #89
Opened 2017-04-28 18:23 UTC by ItsLastDay

@dzharkov 
Checkstyle ругается, но я полагаю, что он здесь не в тему.

2017-05-13 08:37 UTC, dzharkov requested changes
Жду исправлений до 19.05.2017 23:59

2017-05-13 08:37 UTC, dzharkov commented on src/main/java/ru/spbau/mit/MemoryLeakLimit.java
> +                statement.evaluate();
А если случится исключение?
Не забудь тест написать
-1

2017-05-18 17:51 UTC, ItsLastDay commented
Добавил сохранение exception-а. Добавил тест, на котором предыдущая моя версия работает неправильно.

2017-05-21 07:33 UTC, dzharkov commented
Круто, +1 балл
Ок, 10/10

2017-05-21 07:33 UTC, closed without merging