Java01. 06 - memory limit, Павел Бегунков, подгруппа 1
java-course-au/assignments-2017-1 pull request #91
Opened 2017-04-28 22:52 UTC by ISilence

2017-05-13 08:36 UTC, dzharkov requested changes
Жду исправлений до 19.05.2017 23:59

2017-05-13 08:36 UTC, dzharkov commented on src/main/java/ru/spbau/mit/MemoryLeakLimit.java
> +                statement.evaluate();
А если случится исключение?
Не забудь тест написать
-1

2017-05-16 22:38 UTC, ISilence commented
@dzharkov, добавил тесты.
Небольшое копание в исходном коде тест. системы показывает, что проверка на expected проверяется в самом вложенном вызове `evaluate`, и, добавляя над ними правила, не получится что-либо испортить.

2017-05-17 07:58 UTC, dzharkov commented
@ISilence Это указано где-то явно в описании/javadoc'е?
Если нет, то это очень хрупкий аргумент.
К тому же, если пользоваться рулом `ExpectedException`, то что-то мне подсказывает, что порядок зависит от порядка объявления полей в тестовом классе

2017-05-21 07:34 UTC, dzharkov commented
Ок, 10/10

2017-05-21 08:18 UTC, closed without merging