Java01. MemoryLeakLimit,Симиютин Борис, подгруппа 1
java-course-au/assignments-2017-1 pull request #95
Opened 2017-05-04 21:00 UTC by simiyutin

2017-05-13 08:41 UTC, dzharkov requested changes
Жду исправлений до 19.05.2017 23:59

2017-05-13 08:41 UTC, dzharkov commented on src/test/java/ru/spbau/mit/MemoryLeakLimit.java
> +                statement.evaluate();
А если случится исключение?
Не забудь тест написать
-1

2017-05-13 08:41 UTC, dzharkov commented on src/test/java/ru/spbau/mit/MemoryLeakLimitTest.java
> +    public void testMemoryLeakLimitFail() {
Тест не падает

2017-05-13 08:41 UTC, dzharkov commented on src/test/java/ru/spbau/mit/MemoryLeakLimitTest.java
> +    public void testMemoryLeakLimitFail() {
Возможно стоит больше памяти выделять

2017-05-19 20:47 UTC, simiyutin commented on src/test/java/ru/spbau/mit/MemoryLeakLimitTest.java
> +    public void testMemoryLeakLimitFail() {
Видимо, из-за хитрой работы джава машиины, у меня freeMemory после выделения памяти только увеличивался
Переделал подсчет и увеличил количество выделяемой памяти

2017-05-19 20:48 UTC, simiyutin commented on src/test/java/ru/spbau/mit/MemoryLeakLimit.java
> +                statement.evaluate();
Поправил

2017-05-21 07:35 UTC, dzharkov commented
Круто, +1!
10/10

2017-05-21 07:35 UTC, closed without merging